(PXP-9480): Improve sync_single_user_visas performance
uc-cdis/fence pull request #1005
Opened 2022-02-11 19:38 UTC by johnfrancismccann

Jira Ticket: [PXP-9480](https://ctds-planx.atlassian.net/browse/PXP-9480)

Improvements to `sync_single_user_visas` will result in better performance for DRS endpoint, RAS login, and Access Token Polling.

Corresponding PRs
- [gen3authz](url)
- [Arborist](url)

### Improvements
- Significantly improve `sync_single_user_visas` performance by use of a single Arborist policy to represent access

### Dependency updates
- Bump `gen3authz` to `1.5.0`

2022-02-11 22:24 UTC, Avantol13 requested changes

2022-02-11 22:24 UTC, Avantol13 commented on fence/sync/sync_users.py
> +                        return False
let's add some logs here so if this happens we have some stuff to look back at - we may also want to update the error message logged from the calling function when this returns False - I'm not sure if it says "couldn't update Arborist resources" we should make it generic like "something went wrong when updating Arborist". 

We also may want to consider if it's a problem if this breaks part way through. I think it's fine.. but we need to make sure that a partial update doesn't unintentionally have a side-effect.

And does it make sense to completely die immediately upon a single error or should we continue and attempt the rest of the updates and return False at the end if any failed?

I think usersync has had that philosphy, update everything we can and don't die part way through, then return false exit(1), whatever, at the end if anything went wrong. That way, if there's a critical authorization update that for whatever reason would happen _after_ some error, it would still go through

2022-02-11 22:24 UTC, Avantol13 commented on fence/sync/sync_users.py
> +                for roles, resources in unique_policies.items():
so all this is the same as before, just using unique_policies now?

2022-02-11 22:24 UTC, Avantol13 commented on fence/sync/sync_users.py
> +        Wrapper around gen3authz's grant_user_policy with additional logging
all these wrapper functions, while internal to sync, might be better organized into a utils file, maybe in fence/sync/utils.py?

2022-02-11 22:24 UTC, Avantol13 commented on fence/sync/sync_users.py
> +        policies = {}
should we use an OrderedDict here?

2022-02-11 22:24 UTC, Avantol13 commented on fence/sync/sync_users.py
> +        policies = {}
or maybe this doesn't really matter so long as the roles and resources within this are ordered. B/c we'll hash each entry separately

2022-02-11 22:24 UTC, Avantol13 commented on fence/sync/sync_users.py
> +    def _hash_policy_contents(self, roles, resources):
for clarity and to avoid any future issues with using this in a reliable way, can we name the inputs `ordered_roles` and `ordered_resources` like you have elsewhere? Alternatively, we could do the `sorted()` in here

2022-02-14 16:25 UTC, johnfrancismccann commented on fence/sync/sync_users.py
> +                for roles, resources in unique_policies.items():
Yep, the block nested under `for resource in resources:` is almost the same as the old block nested under ` for path in paths:`, except that there's now no code for policy prefixes (which weren't used by usersync anyway) and the granting of a policy is now done with a gen3authz wrapper function.

2022-02-14 17:48 UTC, johnfrancismccann commented on fence/sync/sync_users.py
> +                        return False
I think the worst thing that could happen with a partial update is that there are resources and/or policies lying around in Arborist that aren't actually granted to any users.

I think it would be better to continue and attempt the rest of the updates. If Arborist was temporarily down only during the request for policy creation, the granting of a policy could succeed if the policy already existed from a prior DRS request.

2022-02-15 16:12 UTC, johnfrancismccann commented on fence/sync/sync_users.py
> +        Wrapper around gen3authz's grant_user_policy with additional logging
The only challenge with this is that these wrapper functions use instance variables `self.arborist_client` and `self.logger`.

2022-02-15 16:16 UTC, johnfrancismccann commented on fence/sync/sync_users.py
> +                        return False
How do you feel about having the logs be in those wrapper functions? Might be a personal preference, but I was trying to keep logging and try/except logic in the wrapper functions in the hope that it would make the higher-level code more concise.

2022-02-15 17:05 UTC, Avantol13 approved these changes

2022-02-15 21:43 UTC, merged