PXP-10113 Client credentials grant
uc-cdis/fence pull request #1033
Opened 2022-08-03 22:06 UTC by paulineribeyre

Jira Ticket: [PXP-10113](https://ctds-planx.atlassian.net/browse/PXP-10113)

⚠️ "Client credentials" tokens are not supported by all endpoints, only by the ones needed for the driving use cases

### New Features
- Support the OAuth2 "client credentials" grant
- Support "client credentials" tokens that are not linked to a user in the presigned URL endpoint for files in S3

### Improvements
- `fence-create client-create` now outputs the whole stacktrace in case of error

### Deployment changes
- Requires a Fence DB migration (`Client.redirect_uri` is now optional)

2022-08-10 21:00 UTC, Avantol13 commented on README.md
> +As a Gen3 commons administrator, if you want to create an oauth client for a client credentials flow:
we may want more docs than this, or an explanation of when you might want this (and how authorization is applied the same as users and this only works against certain endpoints)

2022-08-10 21:06 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +            token = validate_request(scope=[], audience=config.get("BASE_URL"))
we may want to consider a scope for client-level information similar to `user`, maybe `client`. I'm not sure when we wouldn't provide this though.. and if the spec doesn't dictate then maybe it's not necessary

2022-08-10 21:08 UTC, Avantol13 commented on fence/jwt/token.py
>  def generate_signed_access_token(
we're not actually allowing client credentials tokens to generate signed URLs, right? All these changes are just to ensure that a sane 401 is returned (instead of 500-ing off of all the user specific access stuff) and pave the road for potentially adding that support in the future?

2022-08-10 21:09 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        given_acls = set()
Okay so my read of this is that we're not actually allowing client credentials tokens to generate signed URLs, right? All these changes are just to ensure that a sane 401 is returned (instead of 500-ing off of all the user specific access stuff) and pave the road for potentially adding that support in the future?

2022-08-10 21:12 UTC, Avantol13 commented on fence/models.py
> +            logger.error(f"Invalid scopes: 'openid' not in requested scopes ({scopes})")
This is one of those error lines that I imagine you added after hours of frustration trying to figure out why something wasn't working, lol. Or at least that's what it'd be for me

2022-08-10 21:13 UTC, paulineribeyre commented on fence/models.py
> +            logger.error(f"Invalid scopes: 'openid' not in requested scopes ({scopes})")
yes 😄

2022-08-10 21:14 UTC, paulineribeyre commented on fence/blueprints/data/indexd.py
> +        given_acls = set()
it does work (s3 only) if the client has read-storage access to the resource. we can block it if you would rather we do that though

2022-08-10 21:14 UTC, Avantol13 commented on fence/oidc/grants/client_credentials_grant.py
> +    pass
why the declaration and pass here? Why not just import from authlib?

2022-08-10 21:15 UTC, Avantol13 commented on fence/oidc/jwt_generator.py
> +    keypair = flask.current_app.keypairs[0]
docstring please

2022-08-10 21:19 UTC, Avantol13 commented on fence/oidc/jwt_generator.py
> +def generate_client_response(client, expires_in=None, scope=None, **kwargs):
the validation checks happen before this, right? This is never called from anywhere before validation of the token? I assume so (I can't see where it wouldn't be) but I just want to double check

2022-08-10 21:23 UTC, Avantol13 commented on fence/sync/sync_users.py
> +            # TODO return an error code so usersync doesn't fail silently
does changing the `return` to `raise` break a bunch of automated tests? why not just do this now

2022-08-10 21:24 UTC, Avantol13 commented on fence/utils.py
> +from cgitb import grey
what is this for? it doesn't look like it's used

2022-08-10 21:26 UTC, Avantol13 commented on fence/utils.py
> -    grant_types = grant_types
:D I want to `git blame` but I won't. mostly because I'm afraid it might have been me

2022-08-10 21:26 UTC, Avantol13 commented on fence/utils.py
> +
thank you for more whitespace for readability :tada:

2022-08-10 21:28 UTC, Avantol13 commented on migrations/versions/e4c7b0ab68d3_create_tables.py
> +        sa.Column("redirect_uri", sa.Text(), nullable=False),
wait, why are we changing existing revisions - isn't the idea that we always create a new revision to update/downgrade what we need to change?

2022-08-10 21:33 UTC, Avantol13 commented on tests/conftest.py
> +):  # app, db_session, oauth_user, get_all_shib_idps_patcher):
dead comment, we can remove?

2022-08-10 21:54 UTC, Avantol13 commented on tests/data/test_data.py
> +def test_download_s3_file_with_client_token(
wait we are allowing data download from clients? Is this a driving requirement? I guess I'm maybe misremembering, but I had it in my head that we were actually NOT going to allow this to start with

2022-08-10 21:59 UTC, Avantol13 requested changes
see comments

2022-08-10 22:02 UTC, paulineribeyre commented on tests/data/test_data.py
> +def test_download_s3_file_with_client_token(
it's not a driving requirement. without thinking that's the endpoint i used to test that things were working. since it was working i left it in

2022-08-10 22:03 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        given_acls = set()
ehhh, I feel like we want to restrict client direct access to data until we absolutely need to support it. Least privilege and all that.

2022-08-11 17:12 UTC, paulineribeyre commented on fence/blueprints/data/indexd.py
> +            token = validate_request(scope=[], audience=config.get("BASE_URL"))
good point - since we're not allowing client tokens for these endpoints anyway, i'm leaving this as-is so we don't complicate things. let me know if you think we should add the scope.

2022-08-11 19:48 UTC, paulineribeyre commented on fence/oidc/grants/client_credentials_grant.py
> +    pass
i assumed i'd need to overwrite something, but i didn't 😆 i'll update this

2022-08-11 21:29 UTC, paulineribeyre commented on fence/sync/sync_users.py
> +            # TODO return an error code so usersync doesn't fail silently
i would rather not do that in this PR because i haven't tested it

2022-08-12 14:31 UTC, paulineribeyre commented on migrations/versions/e4c7b0ab68d3_create_tables.py
> +        sa.Column("redirect_uri", sa.Text(), nullable=False),
you're right but i wasn't sure what to do

`redirect_uri` is supposed to be required at the moment. I think what happened is that i was working on the client-credentials feature before starting work on the alembic feature, so i had made this change to my local db and alembic picked it up when generating the initial migration 🤦‍♀️ 

the migration to make it nullable doesn't fail if it is already nullable, so i think i can revert this change 🤦‍♀️

2022-08-12 15:14 UTC, paulineribeyre commented on fence/oidc/jwt_generator.py
> +def generate_client_response(client, expires_in=None, scope=None, **kwargs):
i only see it called by authlib, which does validate the client ID and secret before generating the token:
```
Fence `POST /token`
=> authlib `AuthorizationServer.create_token_response`
   => first authlib `ClientCredentialsGrant.validate_token_request`
   => then authlib `ClientCredentialsGrant.create_token_response`
      => authlib `ClientCredentialsGrant.generate_token`
         => Fence `jwt_generator.generate_token`
            => Fence `jwt_generator.generate_client_response`
```

2022-08-12 19:01 UTC, UchicagoZchen138 commented on fence/jwt/token.py
> +    sub = None
why do we initalize sub here? Should we remove it?

2022-08-12 19:02 UTC, UchicagoZchen138 commented on fence/models.py
> +        supported_grant_types = [
can we turn this into an enum?

2022-08-15 15:03 UTC, Avantol13 approved these changes

2022-08-15 15:04 UTC, Avantol13 approved these changes

2022-08-15 15:21 UTC, paulineribeyre commented on fence/models.py
> +        supported_grant_types = [
how would it be more flexible? unless it's really needed i prefer to go for the simpler solutions

2022-08-15 19:37 UTC, merged