Feature/bucket info endpoint
uc-cdis/fence pull request #1083
Opened 2023-03-30 19:02 UTC by BinamB

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features
- Add new endpoint, `/bucket_info/region`, that exposes bucket-region mapping from the fence-config

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2023-03-31 15:02 UTC, Avantol13 requested changes

2023-03-31 15:02 UTC, Avantol13 commented on fence/blueprints/bucket_info.py
> +    "/region",
maybe the endpoint should just return all bucket info and not just filter out to the regions

2023-03-31 15:02 UTC, Avantol13 commented on tests/test_bucket_info.py
> +    res = client.get("/bucket_info/region")
docstring please, quickly describing what you're testing

2023-04-03 16:12 UTC, paulineribeyre commented on tests/test_bucket_info.py
> +    assert len(bucket_info["GS_BUCKETS"]) == 2
can you also check that the actual values match?

2023-04-04 14:54 UTC, BinamB commented on fence/blueprints/bucket_info.py
> +    "/region",
We have stuff like `cred` for the bucket in our config https://github.com/uc-cdis/fence/blob/master/fence/config-default.yaml#L634. I dont see it on our public configurations so I havent really seen one in use in any environments so was just trying to be careful.
https://github.com/uc-cdis/fence/blob/master/fence/config-default.yaml#L634

2023-04-05 15:59 UTC, Avantol13 commented on fence/blueprints/bucket_info.py
> +    "/region",
Yeah I guess filtering out the cred is probably smart. But I'd maybe reverse the logic to not only include region, but instead, filter out cred and role-arn. Leaving `endpoint_url` is probably helpful. 

I guess either way making it so that the `endpoint_url` and `region` are there is good

2023-04-24 16:48 UTC, paulineribeyre submitted a review, later dismissed

2023-04-26 14:28 UTC, frankliuao commented
Wait until Alex's PR gets merged before we merge this one. Talked about at the DCF standup on 04.26

2023-04-27 17:16 UTC, frankliuao commented on fence/blueprints/data/blueprint.py
> +    S3_BUCKETS = config.get("S3_BUCKETS", {}).copy()
If I understand correctly the `del` was trying to remove/update the config items from the original config although the operation was done with a copied object? Since the `buckets[bucket] = info_copy` replaces the older object with the new one, I think `copy` should work too? Actually it makes sure `info_copy` is always synced with the original in case something gets updated during this process? But I think I see your point of directly working on the original. Maybe Binam was being very safe here.

2023-04-27 17:28 UTC, frankliuao commented on tests/test_bucket_info.py
> +            "bucket1": {"region": "us-east-1"},
Probably ain't a big deal but I think GS regions go like US-EAST1

2023-04-28 19:44 UTC, BinamB commented on tests/test_bucket_info.py
> +            "bucket1": {"region": "us-east-1"},
There's not a standard way of representing bucket region yet. Im probably going to keep it the same as aws for now just for consistency

2023-05-01 20:21 UTC, Avantol13 approved these changes

2023-05-02 20:24 UTC, Avantol13 submitted a review, later dismissed

2023-05-05 21:17 UTC, MaribelleHGomez approved these changes

2023-05-05 21:17 UTC, merged