Chore/enable client creds on downloads
uc-cdis/fence pull request #1104
Opened 2023-06-08 20:26 UTC by george42-ctds

Jira Ticket: [HP-1133](https://ctds-planx.atlassian.net/browse/HP-1133)

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

* Enable client-credentials on /download/{guid} and /ga4gh/drs/v1/objects/{guid}/access/{access_id} endpoints 

### Dependency updates

### Deployment changes

[HP-1133]: https://ctds-planx.atlassian.net/browse/HP-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-09 18:14 UTC, paulineribeyre commented on tests/data/test_data.py
> +    used to download data from S3 if the indexd_record has an `authz` field.
```suggestion
    used to download data from S3 if the indexd_record has an `authz` field, and that the `client_id` is used to sign.
```

2023-06-09 18:14 UTC, paulineribeyre commented on tests/data/test_data.py
> +    used to download data from S3 if the indexd_record has an `authz` field.
^ copying the original comment from https://github.com/uc-cdis/fence/pull/1033/commits/108fa7535364e6ba01299f80fa72f5fff60052bd#diff-026339dfebdb32c48aea006a3f5317b4b67caf2ef87cc7a8127ea811e71af697R1862-R1869

2023-06-12 15:58 UTC, Avantol13 reviewed
Do we want this behind a configuration flag? It's possible some commons may want to allow clients to do this and others only want end-users to access data in this way.

2023-06-12 18:40 UTC, paulineribeyre reviewed
lgtm, and we can add a config flag if necessary

2023-06-20 17:41 UTC, george42-ctds commented
Optional config flag CLIENT_CREDENTIALS_ON_DOWNLOAD_ENABLED has been added. Default is `false`. 

Unit tests now test flag=true and flag=false.

2023-06-20 18:12 UTC, Avantol13 requested changes

2023-06-20 18:12 UTC, Avantol13 commented on fence/config-default.yaml
> +# set to true to enable client credentials on download/{guid}
Can you update this comment and add a test for the ga4gh endpoint too? I believe it should automatically work with this b/c it just calls these functions. But we should explicitly document that and have a test for it https://github.com/uc-cdis/fence/blob/3cc55b36c5dbedfb4c96b69016625a3b4fbaff6d/fence/blueprints/ga4gh.py#L1-L44

2023-06-27 20:14 UTC, george42-ctds commented on fence/config-default.yaml
> +# set to true to enable client credentials on download/{guid}
Oh, yes, correct, this also now enables the ga4gh endpoint. Test has been added.

2023-06-27 20:34 UTC, Avantol13 approved these changes

2023-06-29 01:18 UTC, merged