feat(DCF-1446): Assign MFA policy on login
uc-cdis/fence pull request #1106
Opened 2023-06-28 22:26 UTC by k-burt-uch

Adds the mfa_policy on login when the configured claim and value are present in the user's id_token.

### New Features
- Enables support for identifying when users have authenticated with MFA.  

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes
For commons interested in MFA enforcement for files: 
user.yaml will need the following added to its policies section: 
 ```    
 - id: mfa_policy
    resource_paths:
    - /multifactor_auth
 ```
And the following added to the resources section: 
```
  - description: data files requiring mfa
    name: multifactor_auth
```
As well as the multifactor_auth_claim_info in fence-config.yaml filled out for the appropriate IdP.

2023-06-28 22:28 UTC, k-burt-uch commented on fence/blueprints/login/ras.py
> +        super(RASCallback, self).post_login(token_result=token_result)
This says token_result but the return value from get_user_id isn't the id_token, its just a dict containing the username or email or both depending on the IdP used. I tagged the mfa property into that dict.

2023-06-28 22:32 UTC, k-burt-uch commented on fence/resources/openid/cilogon_oauth2.py
> +                return {"sub": claims["sub"], "mfa": self.has_mfa_claim(claims)}
This is the weird part I mentioned in our 1-1 @Avantol13. This has nothing to do with getting the user's id like the method name implies but it is the only place where the idp_oauth2 implementations reach out and grab tokens.

Should I split up this method into two parts: get_tokens and get_user_id? My thinking is since this is used in base.py, it'd be a simple refactor to call get_tokens with the authorization code, return the tokens from there, then call get_user_id with the id_token instead of the authorization_code.

2023-06-29 17:03 UTC, Avantol13 commented on fence/blueprints/login/base.py
> +        app=flask.current_app,
is there a reason for this vs `from flask import current_app` at the import level of the module?

2023-06-29 17:08 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
> +        if mfa_claim_info is None:
you could be "truthy" here instead of explicitly checking None. That would early return on an empty dict too.

`if not mfa_claim_info: return False`

2023-06-29 17:08 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
> +        claim_name = mfa_claim_info["claim"]
does the config get validated before this? Or could this fail if someone mistypes the config? 

I'd either: validate before, or be safely trying to access and logging if you can't find something here

2023-06-29 17:09 UTC, Avantol13 commented on tests/login/test_base.py
> +    monkeypatch.setitem(
quick dosctring

2023-06-29 17:09 UTC, Avantol13 commented on tests/login/test_base.py
> +    app.arborist = MagicMock()
quick docstring

2023-06-29 17:18 UTC, Avantol13 requested changes

2023-06-29 17:18 UTC, Avantol13 commented on fence/resources/openid/cilogon_oauth2.py
> +                return {"sub": claims["sub"], "mfa": self.has_mfa_claim(claims)}
Yeah it is a bit odd, the idea I assume was to abstract the different places information can be in tokens to some "standard" return that we can generically read from. The confusing part is a) that it's not just the user_id, you're right and b) that it's a dict and not a well-defined object of some kind.

 I'd almost just rename this to something like `get_standard_authentication_info` or something. Because I do appreciate the abstraction of parsing any needed info from the tokens and returning a simple representation.
 
 idk I'm open to your thoughts here

2023-07-11 19:15 UTC, BinamB commented on fence/config-default.yaml
>      # if mock is true, will fake a successful login response for login
Could you add an example of what the `is-mfa_enabled` param would look like in the default config. Maybe have it disabled in the test config too and enable it during the test, which you've already done

2023-07-11 19:15 UTC, BinamB commented on fence/blueprints/login/base.py
> +                logger.info(f"Revoking mfa_policy for {username}")
Open to your opinion but should we remove mfa_policy regardless of whether or not `is_mfa_enabled` is true. Im just thinking about a case where it was turned on and then turned off and the user still has the mfa policy

2023-08-03 14:55 UTC, Avantol13 commented on fence/resources/openid/cilogon_oauth2.py
> +                return {"sub": claims["sub"], "mfa": self.has_mfa_claim(claims)}
I say leave it, might avoid some confusion in the future

2023-08-03 14:57 UTC, Avantol13 commented on fence/sync/sync_users.py
> +    def _revoke_all_policies_preserve_mfa(self, user):
where is actually called from?

2023-08-03 17:51 UTC, k-burt-uch commented on fence/sync/sync_users.py
> +    def _revoke_all_policies_preserve_mfa(self, user):
whoops

its called from here https://github.com/uc-cdis/fence/pull/1106/files#diff-5824dff91d0ccd46626b8d7fbb03bcc2eb6882c9c038139c48ccfd8c39082d70R2005

2023-08-03 19:41 UTC, k-burt-uch commented on fence/blueprints/login/base.py
> +                logger.info(f"Revoking mfa_policy for {username}")
Revisiting this: I reverted my changes here. I think its better if usersync cleans up the mfa_policy if mfa is turned off rather than during login.

2023-08-03 19:43 UTC, Avantol13 commented on fence/blueprints/login/base.py
> +                    self.app.arborist.revoke_user_policy(
If MFA is enabled but they've never had an MFA policy added before and they don't use MFA, does this error out here? e.g. does revoke_user_policy "fail" silently if the policy doesn't exist for the user?

2023-08-03 19:46 UTC, Avantol13 approved these changes

2023-08-03 22:03 UTC, paulineribeyre commented on tests/login/test_idp_oauth2.py
> +    assert not has_mfa
```suggestion
    assert not has_mfa

    has_mfa = oauth_client.has_mfa_claim({"something": "mfa"})
    assert not has_mfa
```

2023-08-04 18:39 UTC, BinamB submitted a review, later dismissed

2023-08-04 19:44 UTC, k-burt-uch commented on fence/blueprints/login/base.py
> +                    self.app.arborist.revoke_user_policy(
It doesn't error, there's just a log that appears saying the user doesn't have this policy

2023-08-04 20:02 UTC, k-burt-uch commented on fence/sync/sync_users.py
> +            if not has_revoked_policies:
I'm worried (maybe overly so) the call to self.arborist_client.list_resources_for_user(username) may fail and the revoke_all_policies call won't go out.

2023-08-04 20:44 UTC, paulineribeyre commented on fence/sync/sync_users.py
> +            if not has_revoked_policies:
if you pull those calls out of the `try` block, i think usersync will just fail in this ^ case

but if you're really worried, i think this would work too:
```
is_mfa_enabled = ...
etc

try:
    resources = self.arborist_client.list_resources_for_user(username)
finally:
    self.arborist_client.revoke_all_policies_for_user(username)

if "/multifactor_auth" in resources:
    try:
        self.arborist_client.grant_user_policy(username, "mfa_policy")
    except Exception as e:
        self.logger.error(f"Error attempting to preserve MFA policy. {e}")
```

not a big deal. i just think shorter `try` blocks are easier to maintain and debug

2023-08-23 18:38 UTC, Avantol13 commented on fence/config-default.yaml
> +      claim: '' # claims field that indicates mfa, usually the acr or acm claim.
this says "usually" but there's a check later that errors if it's not acr or acm

2023-08-23 19:40 UTC, k-burt-uch commented on fence/config-default.yaml
> +      claim: '' # claims field that indicates mfa, usually the acr or acm claim.
Fixed.

2023-08-23 19:47 UTC, Avantol13 submitted a review, later dismissed

2023-08-23 19:53 UTC, paulineribeyre commented on fence/config.py
> +                )
logging the name of the idp causing the issue, for easier debugging

```suggestion
        for idp_id, idp in self._configs.get("OPENID_CONNECT", {}).items():
            mfa_info = idp.get("multifactor_auth_claim_info")
            if mfa_info and mfa_info["claim"] not in ["amr", "acr"]:
                logger.warning(
                    f"IdP '{idp_id}' is using multifactor_auth_claim_info '{mfa_info['claim']}', which is neither AMR or ACR. Unable to determine if a user used MFA. Fence will continue and assume they have not used MFA."
                )
```

2023-08-23 19:53 UTC, paulineribeyre commented on docs/fence_multifactor_authentication_guide.md
> +To restrict access to files to user who've authenticated with MFA, the following resource *MUST* be present for indexd record:
```suggestion
To restrict access to files to user who've authenticated with MFA, the following resource *MUST* be present in the indexd record's `authz`:
```

2023-08-23 19:53 UTC, paulineribeyre commented on fence/sync/sync_users.py
> +            status_code = self.arborist_client.grant_user_policy(username, "mfa_policy")
sorry for bringing this up late in the review process, but i think this should be more robust:
- we assume that a user having the `/multifactor_auth` resource always means they have the exact `mfa_policy` we expect
- i just noticed in the docs that we assume the `mfa_policy` has been created before enabling MFA and running usersync. If that's not the case, in the current state i think usersync will fail? We should at least make sure the `grant_user_policy()` statement doesn't break usersync if the `mfa_policy` doesn't exist but the user got the `/multifactor_auth` resource some other way.

Why don't we create the policy during usersync?
```
whether "auto_mfa_policy" exists or not, create or update it
revoke_all_policies_for_user()
if "auto_mfa_policy" in gen3authz.get_user()["policies"]:
    grant_user_policy(username, "auto_mfa_policy")
```
The only downside i see is if we need the `mfa_policy` to give different access in different Commons

2023-08-24 22:02 UTC, k-burt-uch commented on fence/sync/sync_users.py
> +            status_code = self.arborist_client.grant_user_policy(username, "mfa_policy")
grant_user_policy just logs an error if the request has anything other than 204 response code 
https://github.com/uc-cdis/gen3authz/blob/master/python/src/gen3authz/client/arborist/base.py#L810

So it won't break user_sync if the policy isn't configured in user.yaml. Worst case, we'll fail secure and /multifactor_auth data isn't accessible until the user.yaml is updated.  

> The only downside i see is if we need the mfa_policy to give different access in different Commons

Yeah, I'm trying to avoid hardcoding the permissions to mfa_policy because I wasn't positive of the needs of other commons and DCF's permissions may need to change later. 

Great tip on checking the policies in user though. I updated this code to not rely on the resource.

2023-08-24 22:06 UTC, paulineribeyre submitted a review, later dismissed

2023-08-25 14:25 UTC, paulineribeyre commented on .travis.yml
> +    - postgresql
since the default is 9.2, do we need to set the version? https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version
i'm not sure which version we use in prod but probably 9.6 since that's what we had on here

2023-08-25 14:57 UTC, Avantol13 commented on .travis.yml
> +    - postgresql
Yeah as far as I know, we were on >=9.6. We rely on something specific that was introduced around JSON or BYTES fields, I can't remember

2023-08-25 15:11 UTC, k-burt-uch commented on .travis.yml
> +    - postgresql
I checked dcf prod and we use version 13 - but I couldn't find anything in cloud-automation that has the postgresql version set :(

2023-08-25 16:02 UTC, k-burt-uch commented on .travis.yml
> +    - postgresql
alright I think I got postgresql-13 working with jammy. Had to steal a lot of code from NCI-GDC's repo https://github.com/NCI-GDC/psqlgraph/

2023-08-25 16:28 UTC, paulineribeyre approved these changes

2023-08-25 16:35 UTC, merged