(feat): Add bucket selection support for multi part upload
uc-cdis/fence pull request #1112
Opened 2023-08-15 15:20 UTC by BinamB

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features
- Added upload bucket selection support for multipart upload

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2023-08-23 15:59 UTC, Avantol13 requested changes

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    bucket = params.get("bucket", None)
If should already default to None, you don't need this

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    bucket = params.get("bucket", None)
.get() already returns None if it's not found, so the `, None` is redundant. You could just `.get("bucket")`

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    # TODO add bucket param here
Is this a real TODO? like we need to do something in the future, can we do it now?

If this is just a note for the future in case we need to add things, don't use `TODO`, just say `note: ` or something

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    bucket = params.get("bucket", None)
same as prev comments, can just use .get(

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +        _is_allowed_data_upload_bucket_configured(bucket)
the prefix "is" usually implies a boolean return. can we rename to something like "verify_data_upload_bucket_configuration" ?

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    # TODO add bucket param here
let's not leave any TODOs, if we need to add this now, let's do it. If this is a note for the future in case we have more, don't use `TODO` just say `note: ` or something

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    bucket = params.get("bucket", None)
```suggestion
    bucket = params.get("bucket")
```

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        if bucket is None:
```suggestion
        if bucket:
```

If you use Truthiness, you don't have to worry about `None` being forced instead of empty strings

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        logger.debug(f"Bucket '{bucket}' not in ALLOWED_DATA_UPLOAD_BUCKETS config")
you should use .error here, not .debug because this is a legitimate error we want logged regardless of the log level

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        logger.debug(f"Bucket '{bucket}' not in ALLOWED_DATA_UPLOAD_BUCKETS config")
you could have an additional debug log that spits out the entire ALLOWED config though if you wanted

2023-08-23 15:59 UTC, Avantol13 commented on openapis/swagger.yaml
> +          description: bucket to upload
```suggestion
          description: bucket to upload to
```

2023-08-23 15:59 UTC, Avantol13 commented on openapis/swagger.yaml
> +          description: bucket to upload
```suggestion
          description: bucket to upload to
```

2023-08-23 15:59 UTC, Avantol13 commented on openapis/swagger.yaml
> +          description: bucket to upload
```suggestion
          description: bucket to upload to
```

2023-08-23 15:59 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +            s3_buckets = get_value(
is this logic exactly what `_is_allowed_data_upload_bucket_configured(bucket)` is doing? Can you reuse that here?

2023-11-21 15:26 UTC, Avantol13 requested changes

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +def verify_data_upload_bucket_configuration(bucket):
docstring please

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/multipart_upload.py
> +def initilize_multipart_upload(bucket_name, key, credentials):
refactor name for typo: `initialize`, not `initilize`

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/blueprint.py
> +    bucket = params.get("bucket")
is there a reason you don't run the verify function after this one?

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +            except KeyError:
this error will never happen b/c `DATA_UPLOAD_BUCKET` is part of the default config, so it will always be set, it might just be ''. And this isn't catching the case where the bucket is actually empty ''.  

So you can simplify/fix this whole block with:

```
bucket = bucket or flask.current_app.config["DATA_UPLOAD_BUCKET"]

if not bucket:
    raise InternalError("fence not configured with data upload bucket; can't create signed URL")
```

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        flask.current_app.config,
you don't need to use `get_value` b/c `ALLOWED_DATA_UPLOAD_BUCKETS` is part of the default configuration, which guarantees its existence in the config dictionary. If you're trying to check if it's an empty list, then this isn't catching that either.
```
s3_buckets = flask.current_app.config["ALLOWED_DATA_UPLOAD_BUCKETS"]

if not s3_buckets:
    raise InternalError("ALLOWED_DATA_UPLOAD_BUCKETS not configured")
```

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +            s3_buckets = get_value(
I think you still left a chunk of code you don't need. If you're calling verify you don't need to get the s3_buckets here

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +                bucket = flask.current_app.config["DATA_UPLOAD_BUCKET"]
see previous comment about default configs. this will never KeyError

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +            except KeyError:
see previous comment

2023-11-21 15:26 UTC, Avantol13 commented on fence/blueprints/data/multipart_upload.py
>  def generate_presigned_url_for_uploading_part(
these are all positive tests. I know they were here before, but can you add some for the error cases like when DATA_UPLOAD and/or ALLOWED_DATA_UPLOAD_BUCKETS buckets aren't specified / are empty?

2023-12-01 17:30 UTC, BinamB commented on fence/blueprints/data/indexd.py
> +            except KeyError:
There's a test that deletes that configuration so this will fail. https://github.com/uc-cdis/fence/blob/master/tests/data/test_blank_index.py#L351
I don't think it gets another default value.
Should I just set the test to empty the field rather than delete the config since that would be more realistic?

2023-12-01 17:37 UTC, BinamB commented on fence/blueprints/data/multipart_upload.py
>  def generate_presigned_url_for_uploading_part(
Sounds like my previous comment might resolve this test case? 🤔

2024-01-22 18:43 UTC, lbeckman314 commented
Thanks Binam for your patience, working on the unit tests issues blocking #1115 which targets this branch (let us know if we should specify a different branch to merge into!).

I will update here and in Slack when the tests are running successfully and it's ready for review!

> https://github.com/uc-cdis/fence/pull/1115

2024-04-02 15:17 UTC, MaribelleHGomez submitted a review, later dismissed

2024-04-04 19:04 UTC, Avantol13 approved these changes

2024-04-05 14:59 UTC, merged