Chore/pps-301
uc-cdis/fence pull request #1114
Opened 2023-09-05 16:04 UTC by tianj7

Jira Ticket: TBD

- Describe what this pull request does.
Rewrite Fence project with work with Authlib 1.2.1

### Dependency updates
Update Authlib Version to 1.2.1

2023-09-05 17:30 UTC, Avantol13 commented
update the PR description to include the "Breaking Changes" section, note that a db migration is required

2023-09-05 17:32 UTC, Avantol13 commented on bin/fence_create.py
> +    token_create.add_argument(
is this optional, so it will run without it to work for access tokens?

2023-09-11 17:24 UTC, Avantol13 commented on migrations/models/migration_client.py
> +class MigrationClient(Base, OAuth2ClientMixin):
do you need to inherit here? inheriting from base makes sqlalchemy actually create this table in the database and do other initialization steps. Can we just have this be an isolated class of data?

2023-09-11 17:36 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +    op.alter_column("client", "client_id", nullable=False, type_=sa.String(48))
I assume these are safe operations that automatically migrate existing data?

2023-09-11 17:47 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +    op.add_column("client", sa.Column("client_metadata", sa.Text(), nullable=True))
I'm still a little confused on the overall process. So you're:

1. Add New Columns for client Table
2. Modify Columns for client Table
3. Set value of metadata field (this is confusingly named b/c it does waaay more than just set the metadata field. It copies everything into a new migration_client table from client, then modifies the migration_client table, deletes client, recreates client from migration_client)

I think I'm confused b/c some of the migration happens on the client table before you delete it and do the rest on the migration_client. Why not just do the whole migration on the migration_client, read from client and get in-mem current clients, convert to migration_clients and commit them to that table, then do the swap (delete client, replace with migration_client).

OR alternatively, do you even need the migration_client table? can you just load all current client data into memory, modify the client table schema, and then ensure the data in that table gets loaded? There is a bit more risk there... b/c if we remove all the clients or mess up the db and then the app crashes we lose the in-mem representations.. so maybe the second table is a bit safer

2023-11-27 17:45 UTC, Avantol13 requested changes

2023-11-27 17:45 UTC, Avantol13 commented on fence/models.py
> +    ##Deprecated, Not called anywhere currently
let's remove then

2023-11-27 17:45 UTC, Avantol13 commented on pyproject.toml
> +#https://github.com/pytest-dev/pytest-flask/issues/167
this has been fixed in pytest 1.3.0. How much work would it be to bump to 3.0.0? If you think it's too much, maybe we should make a separate PR after we merge this one..

2023-11-27 17:45 UTC, Avantol13 commented on tests/migrations/test_9b3a5a7145d7.py
> +def test_upgrade(app):
add a quick docstring please

2023-11-27 17:45 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +    copy_client_to_temp_and_clear_data(op)
can you pass in the temp table name? `migration_client`

Just so that it's easy to follow this high level function and it's clear what you're dropping when you 

```
op.drop_table("migration_client")
```

2023-11-27 17:45 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +    conn = op.get_bind()
let's get some docstrings for these functions

2023-11-27 17:45 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +        if "redirect_uris" in metadata:
You can simplify these to:

```
data["redirect_uri"] = metadata.get("redirect_uris")
```

2023-11-27 17:45 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +        if "grant_types" in metadata and metadata["grant_types"]:
I think you can simplify to:

```
data["grant_type"] = "\n".join(metadata.get("grant_types", "")) or ""
```

2024-04-22 17:41 UTC, Avantol13 requested changes

2024-04-22 17:41 UTC, Avantol13 commented on fence/oidc/oidc_server.py
> +        :param request: HTTP request instance
Use Google style docstrings

2024-06-18 15:39 UTC, Avantol13 submitted a review, later dismissed
Thanks for all the hard work on this. Make sure to clearly state in the `Breaking Changes` section of the PR description that this requires a db migration

2024-06-27 20:41 UTC, MichaelLukowski approved these changes

2024-06-27 21:35 UTC, paulineribeyre approved these changes

2024-06-28 13:46 UTC, merged

2024-07-02 15:09 UTC, pieterlukasse commented on fence/oidc/endpoints.py
> +            token, algorithms=["RS256"], options={"verify_signature": False}
why ``"verify_signature": False`?

2024-07-02 16:00 UTC, tianj7 commented on fence/oidc/endpoints.py
> +            token, algorithms=["RS256"], options={"verify_signature": False}
I was just keeping it the same as previous used logic. I believe from this comment that it was done for compatibility reasons https://github.com/uc-cdis/fence/blob/234638e3221ff470fb497113badcfe47ed355654/fence/jwt/validate.py#L130

it's from 3 years ago so we probably need to review this and create a new ticket to address this if appropriate.
https://github.com/uc-cdis/fence/blame/234638e3221ff470fb497113badcfe47ed355654/fence/jwt/validate.py#L130