(PPS-635): chore(security): update urllib3 and related deps
uc-cdis/fence pull request #1132
Opened 2024-01-03 15:27 UTC by Avantol13

Jira Ticket: [PPS-635](https://ctds-planx.atlassian.net/browse/PPS-635)

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates
- update urllib3

### Deployment changes

2024-01-03 17:03 UTC, k-burt-uch approved these changes
Checked this branch out locally in a fresh venv, ran poetry install without issue. pytest ran without issue (just confirming things GH actions already told us hahaha) 

Approved.

2024-01-08 15:40 UTC, k-burt-uch approved these changes

2024-01-11 16:41 UTC, k-burt-uch requested changes
I have some concerns about the storage client abstraction. Given this is a security issue wiht a limited timeframe, its not a show stopper. 

However, TODOs should be associated with JIRA tickets, especially ones related to input sanitization.

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +        TODO Input sanitazion for parameters
Do we have a ticket for this? ?

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +        response = self._get_bucket_by_id(bucket_id)
Is this bucket -> bucket_id -> bucket is just a check that the bucket information we have is up to date with whatever this "viewSystem.adm" endpoint responds with?

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +            msg = "Bucket {0} wasn't found on the database"
```suggestion
            msg = "Bucket {0} wasn't found in the database"
```

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +            msg = "User {0} wasn't found on the database"
```suggestion
            msg = "User {0} wasn't found in the database"
```

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +            msg = "Error trying to change buket permissions for user {0}"
```suggestion
            msg = "Error trying to change bucket permissions for user {0}"
```

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +        TODO Make this robust against possible errors so most of the keys are deleted
Jira ticket

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +        )  # self-signed certificate
? Is this comment meant to indicate that verify should be false if using a self-signed cert?

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/google.py
> +                "here. Another process should create proxy groups for "
Can we point them to the process used or is it so case-by-case there's not really a way to do it? Trying to head off a user-services/dev-oncall question if someone sees this.

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/google.py
> +    def delete_keypair(self, username, access_key):
Are these only cleversafe specific implementations? If so, why are they in the ABC?? There's a lot of unimplemented methods in this implementation of storage client.

2024-01-11 16:41 UTC, k-burt-uch commented on fence/resources/storage/storageclient/google.py
> +                response = g_mgr.add_member_to_group(
Just a double check:
https://github.com/uc-cdis/cirrus/blob/be8631dccf063e3bf4ce702fe81daaf8253fc045/cirrus/google_cloud/manager.py#L1304 

Does this handle API rate limits we might hit so we don't have to worry about that here??

2024-01-11 16:42 UTC, Avantol13 commented on fence/resources/storage/storageclient/cleversafe.py
> +        TODO Input sanitazion for parameters
All this code is copy pasted verbatim from the existing client library

So there's an argument that all this have been here for years. 

I can go through and clean things up, but honestly I avoided touching this at all to preserve a clean history of an exact copy paste from the library.

Let me know what you think

2024-01-11 16:46 UTC, Avantol13 commented on fence/resources/storage/storageclient/google.py
> +                response = g_mgr.add_member_to_group(
It has backoff setup, yeah

2024-01-11 16:47 UTC, k-burt-uch commented on fence/resources/storage/storageclient/cleversafe.py
> +        TODO Input sanitazion for parameters
That's fair. I'll go through and add tickets to the TODO in a separate PR.

2024-01-11 16:50 UTC, Avantol13 commented
https://ctds-planx.atlassian.net/browse/PXP-11238

Ticket to do storageclient cleanup in the future on a separate PR

2024-01-17 15:44 UTC, merged