Chore/metrics
uc-cdis/fence pull request #1156
Opened 2024-07-03 14:50 UTC by emalinowski

### New Features
Added custom metrics

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2024-07-08 16:05 UTC, paulineribeyre commented on fence/auth.py
> +        login_counter.inc()
as per my previous comment: suggesting a gauge instead with all of [these fields](https://github.com/uc-cdis/fence/blob/234638e3221ff470fb497113badcfe47ed355654/fence/blueprints/login/base.py#L158-L161), so we can have counts per granular IDP (not just fence-level, also shib-level and incommons-level) and per downstream OIDC client

2024-07-08 16:05 UTC, paulineribeyre commented on fence/blueprints/ga4gh.py
> +    presigned_urls_ga4gh_drs_counter = metrics.presigned_urls_ga4gh_drs_counter
the DRS counter could also be merged with the generic download counter, if we pass a parameter like `drs=True` to `get_signed_url_for_file`

2024-07-08 16:05 UTC, paulineribeyre commented on fence/metrics.py
> +            app.wsgi_app, {"/metrics": make_wsgi_app(registry=app.prometheus_registry)}
if you have time, i think a unit test that hits the download endpoint for example and then `/metrics` and checks the output would be valuable

2024-07-08 16:23 UTC, Avantol13 requested changes

2024-07-08 16:23 UTC, Avantol13 commented on fence/__init__.py
> -    if config["ENABLE_PROMETHEUS_METRICS"]:
I feel like we probably want a configuration flag for all this stuff, right? We don't want to require using Prometheus for metrics for the community

2024-07-08 16:23 UTC, Avantol13 commented on fence/metrics.py
> +            app.wsgi_app, {"/metrics": make_wsgi_app(registry=app.prometheus_registry)}
Yeah we should definitely add some unit tests, specifically to test that the metrics are getting incremented for the endpoints too

2024-07-08 16:23 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        ).set(size_in_kibibytes)
Oh, nice catch. Yeah we should update the existing log and make sure we differentiate in the new metrics. `action` is `upload` for uploading data and `download` for retrieving data

2024-07-08 16:23 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +        from fence.metrics import presigned_url_download_protocol_gcs_counter
+1

2024-07-08 16:23 UTC, Avantol13 commented on fence/blueprints/ga4gh.py
> +    presigned_urls_ga4gh_drs_counter = metrics.presigned_urls_ga4gh_drs_counter
+1

2024-07-08 16:23 UTC, Avantol13 commented on fence/metrics.py
> +        self.presigned_url_data_metrics_size_gauge = None
+1 to the idea of simplifying the interface here. We could bake more logic in this class vs when we are incrementing things in outside code too. e.g. if it makes more sense to keep these all as separate counters, then just have the metrics class implement a single interface and make decisions on which one to update in the class itself. If I want to add a metric in outside code, I shouldn't have to logic through what specific counter to inc.  

Also these login options don't cover the other IdPs, like Pauline said. So we either need this to be able to dynamically create counters/gauges, or explicitly define one for every IdP we have (I think that's not ideal b/c we have to remember to add here when we add a new IdP too). 

Also, I would ideally like a single line to update a metric (not the current method of assigning var, checking if it exists, and then inc). The repeated assignment and checking is a bit much to be repeated everywhere (it's too much boilerplate code). 

So killing a few birds, maybe implementing higher level function calls to this Metrics class and baking more logic in would be better.

`metrics.add_login(idp=foo)` 

`metrics.add_signed_url(action="download", size_in_kibibytes={size_in_kibibytes}, acl={acl}, authz={authz}, bucket={bucket}, user_sub={user_sub}, client_id={client_id})` or something like this

Then put all the logic of what counters/gauges to deal with in this class; so all the logic of "what counter/guage do I update" is isolated in this file and outside code just requests a metric to be added with whatever relevant metadata (much like the single line log we have right now).

2024-07-08 20:02 UTC, emalinowski commented on fence/auth.py
> +    from fence.metrics import metrics
I was dealing with circular dependency issues when I imported it at the top and importing it before it was called was an easy workaround. I'll see what I can do now though.

2024-07-08 20:02 UTC, emalinowski commented on fence/blueprints/data/indexd.py
> +        from fence.metrics import presigned_url_download_protocol_gcs_counter
I was dealing with circular dependency issues when I imported it at the top and importing it before it was called was an easy workaround. I'll see what I can do now though.

2024-07-08 20:02 UTC, emalinowski commented on fence/metrics.py
> +        self.presigned_url_data_metrics_size_gauge = None
So counters are just incrementing, whereas gauges show set values. So the presigned url gauge is for the download size of each object being downloaded, as that is a likely a different value each time, whereas the logins are counters because they increment up once each time you login. We could definitely have different counters for each login type, but for the moment I just added the ones that were currently in datadog. I'll definitely simplify logins and presigned urls to use labels though so that we can simplify it to one counter each, since I believe counts support labels as well. That's also a good idea about adding the logic to the class and I'll see what I can do to clean that up.

2024-07-23 17:17 UTC, Avantol13 requested changes

2024-07-23 22:00 UTC, paulineribeyre commented on fence/__init__.py
> +        data, content_type = metrics.get_latest_metrics()
yes, and we should add the metrics endpoint to the swagger doc too, with that disclaimer

before we merge this, let's wait for the PR that blocks access to it at the revproxy level

2024-07-23 22:16 UTC, paulineribeyre commented on fence/__init__.py
> +        data, content_type = metrics.get_latest_metrics()
added docstring and endpoint in swagger doc

2024-07-23 22:16 UTC, paulineribeyre commented on fence/metrics.py
> +import os
added docstring

2024-07-26 13:48 UTC, Avantol13 approved these changes

2024-07-26 14:37 UTC, merged