[WIP] Fix/handle none string v2
uc-cdis/fence pull request #1161
Opened 2024-07-18 19:02 UTC by AlbertSnows

Link to JIRA ticket if there is one: 

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2024-07-18 19:40 UTC, mfshao commented on fence/config.py
> +        else:  # assume is a dict
Instead of assuming, why not actually check if `dbgap_configs` is a dict and raise an exception otherwise

2024-07-18 20:04 UTC, AlbertSnows commented on fence/config.py
> +        else:  # assume is a dict
Hmm, yeah I thought about that initially but decided to just minimize the changes. If it were ever not a dict though, that would be useful information. I'll update it!

2024-07-23 15:46 UTC, Avantol13 requested changes

2024-07-23 15:51 UTC, AlbertSnows commented on tests/test_app_config.py
> +        pytest.fail("Study validation failed when it should have passed!")
I don't know how this comment never showed up. I apologize for missing this, I'll get it implemented.

2024-07-23 15:52 UTC, Avantol13 commented on tests/test_app_config.py
> +        pytest.fail("Study validation failed when it should have passed!")
it was sitting on my side as a draft 🤦‍♂️, sorry about that. I just pushed it through this morning

2024-08-07 19:15 UTC, BinamB submitted a review, later dismissed

2024-08-07 19:43 UTC, Avantol13 requested changes

2024-08-07 19:43 UTC, Avantol13 commented on fence/config.py
> +        def get_parent_studies_safely(dbgap_config):
I don't really like nesting function definitions inside another function unless you really need to. In this case I think you should break it out into another helper funcion or just embed the code

2024-08-07 19:43 UTC, Avantol13 commented on fence/config.py
> +    def find_duplicates(collection):
public functions require docstrings

2024-08-07 19:43 UTC, Avantol13 commented on fence/config.py
> +                                       for safe_parent_studies in get_parent_studies_safely(dbgap_config)]
the two for loops in this list comprehension is imo too complicated for easy readability. I'd rather see this written out with one level of nesting if need be. List comprehension is nice when it's really clear what's happening, but I'd rather be explicit in more complicated cases like this and use traditional looping

2024-08-07 19:43 UTC, Avantol13 commented on tests/test_app_config.py
> +def test_validate_parent_child_studies_against_none_config():
tests require docstrings

2024-08-07 19:43 UTC, Avantol13 commented on tests/test_app_config.py
> +        pytest.fail("Study validation failed when given 'None' mapping!")
you can instead do:

```
with pytest.raises(Exception):
    FenceConfig._validate_parent_child_studies(none_string_config)
```

not a big deal but for consistency, the other assertions in the tests do it this way

2024-08-07 19:43 UTC, Avantol13 commented on fence/config.py
> +        dbgap_configs = self._configs["dbGaP"]
I actually liked this logic built into the validation so it doesn't clutter this outer scope of just loading config

2024-08-07 20:10 UTC, AlbertSnows commented on tests/test_app_config.py
> +def test_validate_parent_child_studies_against_none_config():
docstring added

2024-08-07 22:20 UTC, AlbertSnows commented on fence/config.py
> +                                       for safe_parent_studies in get_parent_studies_safely(dbgap_config)]
I am not the biggest fan of list comprehensions either. However, speaking as someone who only learned the syntax recently, I have been able to get use to the syntax without much trouble. There are also other reasons I find compelling to use this over traditional for loops, but I will refrain from listing them all for sake of brevity. As such, I am going to keep the change as is. However, if you are not convinced or otherwise would like to insist let me know and I can make the switch.

2024-08-07 22:34 UTC, AlbertSnows commented on fence/config.py
> +    def find_duplicates(collection):
docstring added

2024-08-07 22:48 UTC, AlbertSnows commented on tests/test_app_config.py
> +        pytest.fail("Study validation failed when given 'None' mapping!")
If I am understanding correctly, that line would cause the test to *pass* if an exception is thrown. This is not what we want. We currently treat 'None' as empty and thus ignore it. So this test should pass and not throw an exception. In which case, I think we just want to use a regular try catch. Let me know if I've misunderstood. I will leave this unresolved just in case.

2024-08-07 22:56 UTC, AlbertSnows commented on fence/config.py
> +        dbgap_configs = self._configs["dbGaP"]
Yeah I'm sympathetic to that view. If you view this as the 'loading/processing' function and the validation function as just generically validating, then that would be the expected approach. The change was motivated by a separation of concern. The validation function is only cares about checking that there are no duplicates, and thus it would be appropriate to remove any logic that asks, "Are you giving me the correct data structure to validate?" 
However, there is an alternative approach. The compromise would be to generalize the validation function, call it V, and have V consist of two steps: checking that the dbgap config is structured correctly, and then check that there are no duplicates. 
I would have done that first, but I didn't want to be overly ambitious since this is just a bug fix. Let me know if you'd rather see that implementation instead though.

2024-08-07 23:06 UTC, AlbertSnows commented on fence/config.py
> +        def get_parent_studies_safely(dbgap_config):
function moved out

2024-08-09 14:38 UTC, Avantol13 requested changes

2024-08-09 14:38 UTC, Avantol13 commented on fence/config.py
> +        dbgap_configs = self._configs["dbGaP"]
Yeah, I would rather see that compromise. imo the validation isn't intended to take the "correct" data structure, it's intended to take the configuration as-is and determine if it's valid. So, to me it makes more sense to have it all encapsulated there

2024-08-09 14:38 UTC, Avantol13 commented on fence/config.py
> +                                       for safe_parent_studies in get_parent_studies_safely(dbgap_config)]
I'm not convinced brevity > readability (and I know that readability is somewhat subjective). Unless that brevity actually results in a significant efficiency gain (and even that needs to be weighed against readability). It's rare to see list comprehensions with multiple for loops (even though you technically can do this) so even for people familiar with the basics, this requires a double take to trace what's actually happening. So I hold my original opinion that we should not do a double for loop in a list comprehension.

2024-08-09 14:38 UTC, Avantol13 commented on tests/test_app_config.py
> +        pytest.fail("Study validation failed when given 'None' mapping!")
Ah, yes, you're totally right, I misread this 👍

2024-08-09 17:37 UTC, AlbertSnows commented on fence/config.py
> +                                       for safe_parent_studies in get_parent_studies_safely(dbgap_config)]
I think you may have misunderstood. Brevity was just referring to listing motivations for the change, it's not a property of the change itself per se. I don't think I see/share your issues with readability, but given the context I'll switch it over.

2024-08-09 17:38 UTC, AlbertSnows commented on fence/config.py
> +        dbgap_configs = self._configs["dbGaP"]
makes sense to me, i'll implement the change

2024-08-09 20:04 UTC, Avantol13 requested changes

2024-08-09 20:04 UTC, Avantol13 commented on fence/config.py
> +    def find_duplicates(collection):
Yeah and actually, since these are static methods of this class, they're not really going to be used elsewhere in a meaningful way. I'd say you should probably preface these with `_` OR *not* have these in the class and then having them "public" is fine (either here or in utils)

2024-08-09 20:04 UTC, Avantol13 commented on fence/config.py
> +    def validate_parent_child_studies(dbgap_configs: List[Dict[str, Any]]) -> None:
actually, I think keeping the _ makes sense. This won't be used elsewhere

2024-08-09 20:04 UTC, Avantol13 commented on fence/config.py
> +    def enforce_is_array(dbgap_configs):
I think this should be _ prefaced. Not really used elsewhere

2024-08-09 23:09 UTC, AlbertSnows commented on fence/config.py
> +            Nothing. This function will throw if duplicates are found.
changed to just a note

2024-08-09 23:09 UTC, AlbertSnows commented on fence/config.py
> +    def validate_parent_child_studies(dbgap_configs: List[Dict[str, Any]]) -> None:
added back _

2024-08-09 23:09 UTC, AlbertSnows commented on fence/config.py
> +        """
sentence added

2024-08-09 23:10 UTC, AlbertSnows commented on fence/config.py
> +    def find_duplicates(collection):
will dm clarifying questions

2024-08-09 23:10 UTC, AlbertSnows commented on fence/config.py
> +    def enforce_is_array(dbgap_configs):
will dm with a question

2024-08-12 18:17 UTC, AlbertSnows commented on fence/config.py
> +    def find_duplicates(collection):
resolved by adding todo's for future work and keeping them in config for now

2024-08-12 18:18 UTC, AlbertSnows commented on fence/config.py
> +    def enforce_is_array(dbgap_configs):
resolved by redesigning functions a bit, keeping them in config, and adding to todos

2024-08-26 14:13 UTC, Avantol13 requested changes

2024-08-26 14:13 UTC, Avantol13 commented on tests/test_utils.py
> +def test_find_duplicates():
docstrings on all functions, including tests, even just a simple "Test the output of the duplicates utility function with expected input"

2024-08-26 14:13 UTC, Avantol13 commented on tests/test_utils.py
> +def test__coerce_to_array():
the __ is a little odd. I know why you did it, but I'd say you keep what you did above and just call it `test_coerce_to_array`

2024-08-26 14:13 UTC, Avantol13 commented on fence/utils.py
> +This file is for functions that are generalized enough to be used in varied places that need not be related.
thanks for adding this

2024-08-26 14:13 UTC, Avantol13 commented on fence/utils.py
> -def hash_secret(f):
was this not used anywhere?

2024-08-26 14:13 UTC, Avantol13 commented on fence/utils.py
> +# TODO(fix-it): this variable should be moved to config.py to remove the reliance on the config
I'm nervous to add a bunch of TODO's for future work that isn't scheduled. I'd say either we expand the scope to include this or you really try to get it done as part of Fix it Friday or something, otherwise this will just stay like this for years

2024-09-03 18:38 UTC, AlbertSnows commented on tests/test_utils.py
> +def test_find_duplicates():
I think i just missed these, should be added now!

2024-09-03 18:38 UTC, AlbertSnows commented on tests/test_utils.py
> +def test__coerce_to_array():
can do

2024-09-03 18:39 UTC, AlbertSnows commented on fence/utils.py
> +This file is for functions that are generalized enough to be used in varied places that need not be related.
you are welcome!

2024-09-03 18:40 UTC, AlbertSnows commented on fence/utils.py
> -def hash_secret(f):
correct, I did not find any uses of it so I removed it, but I can always add it back!

2024-09-03 18:48 UTC, AlbertSnows commented on fence/utils.py
> +# TODO(fix-it): this variable should be moved to config.py to remove the reliance on the config
I will make a fix-it ticket for this, and try to get it done on friday.
as such, i will say let's keep the scope focused. i will mark this as resolved when ticket is made

2024-09-03 18:56 UTC, AlbertSnows commented on fence/utils.py
> +# TODO(fix-it): this variable should be moved to config.py to remove the reliance on the config
https://ctds-planx.atlassian.net/browse/PXP-11392

2025-02-21 19:40 UTC, BinamB commented on fence/config.py
> +        """ Returns the first element that satisfies the predicate, else fail value
```suggestion
        """
         Returns the first element that satisfies the predicate, else fail value
```
Small nitpick

2025-02-21 19:40 UTC, BinamB commented on fence/utils.py
> -def create_client(
Why is create_client moved?

2025-02-21 19:58 UTC, AlbertSnows commented on fence/utils.py
> -def create_client(
i think it was a circular dependency, let me check

2025-02-21 20:22 UTC, AlbertSnows commented on fence/utils.py
> -def create_client(
couldn't recreate so I've moved it back.

2025-02-21 20:47 UTC, BinamB approved these changes

2025-02-28 19:23 UTC, closed without merging