[Proposal(DNM)] Cleaning up fence documentation
uc-cdis/fence pull request #1164
Opened 2024-07-22 17:58 UTC by AlbertSnows

Link to JIRA ticket if there is one: 

### New Features

### Breaking Changes

### Bug Fixes

### Improvements
- Reorganized docs to make finding what you need a bit easier

### Dependency updates

### Deployment changes

2024-07-23 13:55 UTC, Avantol13 commented on docs/introduction/oidc_and_oauth2.md
This overview and diagrams should go in the root README. It's possible we refer to the README in docs about what flows Gen3 supports and I don't want those links to no longer contain this info.

2024-07-23 14:05 UTC, Avantol13 requested changes

2024-07-23 14:05 UTC, Avantol13 commented on README.md
>  ## Access Control / Authz
I'd actually move `## Access Control / Authz` and `## Accessing Data` all this to a new `authorization.md` and add a new bullet to the Table of Contents for it.

2024-07-23 14:05 UTC, Avantol13 commented on README.md
>  ## Access Control / Authz
I'd also move `## Accessing Data` and `### Signed URLS` to another `data_access.md`  and out of here

2024-07-23 14:05 UTC, Avantol13 commented on README.md
This is great, thanks for the effort here. It's been a while since docs cleanup. That being said, I think we have a chance to clean things up even more.

I would structure it like this:

```
Fence overview

## Identity Providers
## OIDC & OAuth2
## Setup
  - You can just link to the other doc. "See detailed explanation [here]()"
## Additional Docs 
  - this is the current "Contents" + additional links for the others sections moved out of the root README (see my other comments)
```

2024-07-23 14:26 UTC, AlbertSnows commented on docs/introduction/oidc_and_oauth2.md
I will remove file and add contents back to readme

2024-07-23 15:00 UTC, AlbertSnows commented on README.md
implemented

2024-07-23 15:01 UTC, AlbertSnows commented on README.md
>  ## Access Control / Authz
I was also not sure what table of contents you would want since the file is so small, so I did not add it. I will keep this open in case you'd like to clarify.

2024-07-23 15:40 UTC, Avantol13 requested changes

2024-07-23 15:40 UTC, Avantol13 commented on README.md
> +### ## API Documentation
```suggestion
### API Documentation
```

2024-07-23 15:40 UTC, Avantol13 commented on README.md
> +See detailed explination [here](docs/additional_documentation/setup.md)
```suggestion
See detailed explanation [here](docs/additional_documentation/setup.md).
```

2024-07-23 15:40 UTC, Avantol13 commented on README.md
> +3. [Setup](docs/additional_documentation/setup.md)
I think you can remove this one since it's in the heading above.

2024-07-23 15:55 UTC, AlbertSnows commented on README.md
oh forgot to mark this as done

2024-07-23 17:50 UTC, AlbertSnows commented on README.md
> +3. [Setup](docs/additional_documentation/setup.md)
fixed a few other typos as well

2024-07-26 20:51 UTC, jacob50231 approved these changes
Some concerns about some paths being changed from absolute to relative but other than that no big deal at all. Just something to keep an eye out for if somebody edits this in the future. Approving!

2024-07-30 14:41 UTC, merged