Remove Foreign Key Constraints for Service Account
uc-cdis/fence pull request #1172
Opened 2024-08-07 21:36 UTC by BinamB

Link to JIRA ticket if there is one: 
Pre-alembic era created a foreign key clent_id(from the client table) on the google_service_account table.
    This foreign key was then removed from the schema but any commons created before the constraint was removed
    still held the foreign key.
    The previous alembic migration tuncates the client table but this fails if the foreign key constraint still persists
    therefore failing the migration.
    This migration checks for the existence of the foreign key constraint and removes it if it exists.
    There is no downgrade path for this since not having the foreign key constraint is the correct schema throughout all versions.
    This migration is specifically for commons that were created before the foreign key constraint was removed
### New Features

### Breaking Changes

### Bug Fixes
- Create new migration to remove foreign key constraint if it exists on google_service_account table
### Improvements

### Dependency updates

### Deployment changes
- Requires database migration

2024-08-08 20:13 UTC, k-burt-uch requested changes

2024-08-08 20:13 UTC, k-burt-uch commented on tests/migrations/test_e695e299f6a6.py
Do we have a way to test that the full alembic migration succeeds? IIRC the migration fails here: 
https://github.com/uc-cdis/fence/blob/master/migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py

Because of this FK constraint. But this only tests if the migration to remove the FK constraint succeeds, not that the collection of migration scripts succeeds.

I think a full migration check is beyond the scope of what you're doing here, but it might be best to move the removal of the FK to the previous migration https://github.com/uc-cdis/fence/blob/master/migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py here instead of adding a new migration.

2024-08-08 20:13 UTC, k-burt-uch commented on migrations/versions/e695e299f6a6_remove_foreign_key_constraint_googleSA.py
Can't we update this migration
https://github.com/uc-cdis/fence/blob/master/migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py

To do this instead of making a new migration?

2024-08-09 15:14 UTC, Avantol13 requested changes

2024-08-09 15:14 UTC, Avantol13 commented on migrations/versions/e695e299f6a6_remove_foreign_key_constraint_googleSA.py
yeah, this won't work. We can't have a new migration b/c the previous one fails. We must update the previous one

2024-08-09 16:28 UTC, Avantol13 submitted a review, later dismissed

2024-08-09 16:28 UTC, Avantol13 commented on migrations/versions/9b3a5a7145d7_authlib_update_1_2_1.py
> +        logger.info("Foreign key client_id does not exist.")
```suggestion
        logger.debug("Foreign key client_id does not exist. This is expected for newer versions of the service.")
```

2024-08-09 17:00 UTC, k-burt-uch approved these changes

2024-08-09 19:49 UTC, merged