Feature/OIDC oauth groups
uc-cdis/fence pull request #1188
Opened 2024-09-26 09:10 UTC by flashguerdon

### New Features

- Support for OIDC Group Claims
- Implementation of token refresh

2024-09-30 17:15 UTC, Avantol13 requested changes
Thanks folks! At a high-level this is a great direction.

Initial round of feedback complete. Light review of the testing at this point (since I expect some of it to change). Suggesting some reorganization and other minor cleanup (see comments).

Please feel free to respond to comments for clarification and/or make updates and let me know once everything has been addressed. I'll do another round of review after that.

2024-09-30 17:15 UTC, Avantol13 commented on tests/login/test_idp_oauth2.py
> -def test_has_mfa_claim_acr(oauth_client_acr):
note to self / future reviewer: removed b/c duplicate

2024-09-30 17:15 UTC, Avantol13 commented on tests/login/test_idp_oauth2.py
> +def mock_app():
these could go in conftest

2024-09-30 17:15 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
> +        self.is_mfa_enabled = "multifactor_auth_claim_info" in self.settings
Do you need this? I'm not seeing why this is necessary outside of the existing logic

2024-09-30 17:15 UTC, Avantol13 commented on fence/blueprints/login/base.py
> +        if self.check_groups:
perhaps check if there's actually config for the group syncing for this client too, not just the global feature flag

2024-09-30 17:15 UTC, Avantol13 commented on fence/config-default.yaml
> +CHECK_GROUPS: false
Okay, giving this some more thought, maybe it makes sense to *not* have this global feature flag, and instead just have the per-client config. That could be a lot cleaner

2024-09-30 17:15 UTC, Avantol13 commented on tests/test-fence-config.yaml
> +    groups:
The naming here makes this a little confusing in the code. Take a look at my previous comments around potential renaming. 

I think we need `is_enabled` true/false if we keep this under a `groups` config, but I feel like it would improve readability if there was a top-level flag turning this on and *then* you can read the config. So have :

```
generic3:
  is_authz_groups_sync_enabled: true
  authz_groups_sync:
    group_prefix: /covid
```

2024-10-07 22:43 UTC, flashguerdon commented on fence/blueprints/login/base.py
> +        self.app = app if app is not None else flask.current_app
The reason was flask.current_app wasn't available on some of the test. But I agree, it is redundant now.

2024-10-08 00:34 UTC, flashguerdon commented on fence/resources/openid/idp_oauth2.py
> +    def decode_token(self, token_id, keys):
This function validates audience.

2024-10-08 04:28 UTC, flashguerdon commented on fence/resources/openid/idp_oauth2.py
> +        self.arborist = ArboristClient(
Requires further investigation, as the arborist client here in not in the app context; hence new client.
RuntimeError: Working outside of application context

2024-10-08 06:12 UTC, flashguerdon commented on fence/error_handler.py
> +    #raise error
Issue: Error messages are obfuscated, the line needs be uncommented when troubleshooting errors. Breaks tests if not commented out / removed. I have added a TODO so this can be looked at.

2024-10-08 23:30 UTC, flashguerdon commented on fence/resources/openid/idp_oauth2.py
> +        self.audience = self.settings.get("audience", self.settings.get("client_id"))
This is in the base class, the settings are for a specific client, so inconsistent clients are covered

2024-10-09 03:14 UTC, flashguerdon commented on fence/resources/openid/idp_oauth2.py
> +        self.is_mfa_enabled = "multifactor_auth_claim_info" in self.settings
removed.

2024-10-11 02:59 UTC, flashguerdon commented on fence/config-default.yaml
> +CHECK_GROUPS: false
Makes sense. Removed the global feature flag

2024-10-11 02:59 UTC, flashguerdon commented on tests/test-fence-config.yaml
> +    groups:
agreed

2024-10-11 13:53 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
> +        self.arborist = ArboristClient(
Are you ever running this class outside of the flask app? If it's happening in tests, you may need to inspect that. The arborist client for Fence gets instantiated here: https://github.com/uc-cdis/fence/blob/0efce95888718161e58359312e2f345e652db446/fence/__init__.py#L478-L480 it's based on a configuration, so you may need to add that to your instance

2024-10-13 02:55 UTC, flashguerdon commented on fence/resources/openid/idp_oauth2.py
> +        self.arborist = ArboristClient(
The issue is with [fence/job/access_token_updater.py](https://github.com/uc-cdis/fence/pull/1188/files#diff-e96202d6bcb84a435f7a97b898fb222fc1cc15597fc58a92a7a812b57769a44a), when running `fence_create.py update-visas` script, get out of the app context via cron job when executing `update_user_authorization` in Oauth2ClientBase, which requires arborist client. Any ideas?

2024-10-16 18:24 UTC, Avantol13 requested changes

2024-10-16 18:24 UTC, Avantol13 commented on fence/job/access_token_updater.py
> +        # Initialise a client for each OIDC client in oidc, which does has gis_authz_groups_sync_enabled set to true and add them
```suggestion
        # Initialise a client for each OIDC client in oidc, which does has is_authz_groups_sync_enabled set to true and add them
```

2024-10-16 18:24 UTC, Avantol13 commented on fence/job/access_token_updater.py
> +            if oidc.get(oidc_name).get("is_authz_groups_sync_enabled", False):
```suggestion
            if oidc.get(oidc_name, {}).get("is_authz_groups_sync_enabled", False):
```

2024-10-16 18:24 UTC, Avantol13 commented on fence/job/access_token_updater.py
> +        for oidc_client in self.oidc_clients_requiring_token_refresh:
this could be slightly more efficient if `oidc_clients_requiring_token_refresh` was a dict of `{"oidc_client.idp": oidc_client}`

2024-10-16 18:24 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
> +                    self.logger(
self.logger.error

2024-10-16 18:24 UTC, Avantol13 commented on fence/blueprints/login/base.py
> +        if self.is_read_authz_groups_from_tokens_enabled:
This could also be done if we simply want to persist the refresh token but not use this read authz groups feature.

So I would propose 2 things:
- Ensure it is obvious in the configuration that enabling `is_read_authz_groups_from_tokens_enabled` also makes it so that Fence persists refresh tokens from that IdP
- Provide a _separate_ config, perhaps `persist_refresh_token`, which is defaulted to False and overrides `is_read_authz_groups_from_tokens_enabled`. This allows an idp who is NOT reading authz groups to request storage of refresh tokens. While this doesn't immediately benefit us here, it is a more flexible configuration for future extensibility

2024-10-16 18:24 UTC, Avantol13 commented on fence/blueprints/login/base.py
> +        Parameters:
we use "Google-style" docstrings, see other examples in Fence or reference the docs: https://google.github.io/styleguide/pyguide.html

2024-10-16 18:24 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
>      def get_jwt_claims_identity(self, token_endpoint, jwks_endpoint, code):
you're modifying the original intent of this function, which was to return the validated claims from the identity (id) token. I understand why you're adding this functionality here (to avoid an additional API call to the token endpoint), but I think we need to update the function name and docstring and consider returning similar formats for the id and refresh token (e.g. one is validated and decoded and one is NOT). 

The fact that the returned refresh token here is not validated is problematic, b/c it's unclear to the caller that they're getting 1 validated token and one non-validated one. And since this is such a high-level and used function, we should rethink this. 

Ideally, this should validate and return the decoded contents. Or rather, perhaps we need to split the logic up here. A function to get the _non-validated, raw_ tokens, and another function to get the ID token claims by passing in the raw token. Then we don't have to make the return of this function so messy

2024-11-05 22:58 UTC, flashguerdon commented on fence/resources/openid/idp_oauth2.py
> +        ###this function is not correct. use self.session.fetch_access_token, validate the token for audience and then return the validated token. Still store the refresh token. it will be needed for
Resolved.

2025-01-08 15:46 UTC, michaelfitzo commented
Hello! Before moving ahead with any final approvals, the engineering team feels that it would be extremely useful to us to hear a bit more background on the request.  We have recently implemented a requirement that PRs must typically include a Community Feature Document, which gives us a bit more background on the request, your requirements, and use cases.  

https://docs.google.com/document/d/1P2dfqnSH-e7OX1Hw62sDL8zcR7gZp4d152TlDBlomDc/edit?usp=sharing

The document looks long, but I would ask you to focus on the requirements and use cases sections along with whatever else you can.  Apologies again for not sending sooner, but I think this will unblock any final reviews required.  Let me know if you have any questions about this

2025-05-30 20:46 UTC, merged