Addition of Okta and a generic OIDC client for authentication options
uc-cdis/fence pull request #828
Opened 2020-08-27 21:14 UTC by cginmn

Using the Microsoft configurations and code, made an Okta and Generic OpenID Connect client.

Description about what this pull request does.

Using the Microsoft code and configuration, made an Okta and a generic OpenID Connect client. 
Create Okta and generic OIDC client endpoint config
fence/resources/openid/okta_oauth2.py
fence/resources/openid/generic_oauth2.py

Create Okta and generic methods
fence/blueprints/login/okta.py
fence/blueprints/login/generic.py

Update Okta and generic OIDC entry
fence/config-default.yaml

Update Okta and generic login route
fence/blueprints/login/__init__.py

Update Okta and generic OIDC client
fence/__init__.py

Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.

### New Features
- Implemented new Okta and generic OIDC clients

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2021-03-17 11:56 UTC, ohofmann commented
A +1 here - we'd be interested in this.

2021-04-14 14:13 UTC, williamhaley requested changes
Thank you for your contributions! To conform to some of our best practices (apologies that this isn't prominent in our docs) can you please run the following to format your code?

```bash
pip install black
python -m black .
```

Overall I think these changes should work, but I've lever several comments to help our code quality analysis tools and to help get some of the tests to pass. Thank you!

2021-04-14 14:13 UTC, williamhaley commented on fence/resources/openid/generic_oauth2.py
> +import json
Unused import.

```suggestion
```

2021-04-14 14:13 UTC, williamhaley commented on fence/blueprints/login/okta.py
> +from fence.models import IdentityProvider
Unused import.

```suggestion
```

2021-04-14 14:13 UTC, williamhaley commented on fence/blueprints/login/generic.py
> +from fence.models import IdentityProvider
Unused import.

```suggestion
```

2021-04-14 14:13 UTC, williamhaley commented on fence/config-default.yaml
> +  okta:
Can you also add these new sections to `test-fence-config.yaml` for the sake of the automated tests?

2021-04-14 14:13 UTC, williamhaley commented on fence/resources/openid/okta_oauth2.py
> +OKTA_IDP_NAME = "okta"
I believe you'll also need to add `okta` to this line in the tests https://github.com/cginmn/fence-service/blob/feat/oidc-client/tests/test_audit_service.py#L366, and to add this...

```
    elif idp == "okta":
        mocked_get_user_id = MagicMock()
        get_user_id_value = {"okta": username}
```

... around here https://github.com/cginmn/fence-service/blob/feat/oidc-client/tests/test_audit_service.py#L336

2021-04-14 14:13 UTC, williamhaley commented on fence/resources/openid/generic_oauth2.py
> +GENERIC_IDP_NAME = "generic"
I believe you'll also need to add `generic` to this line in the tests https://github.com/cginmn/fence-service/blob/feat/oidc-client/tests/test_audit_service.py#L366, and to add this...

```
    elif idp == "generic":
        mocked_get_user_id = MagicMock()
        get_user_id_value = {"generic": username}
```

... around here https://github.com/cginmn/fence-service/blob/feat/oidc-client/tests/test_audit_service.py#L336

2021-04-15 15:43 UTC, cginmn commented on fence/resources/openid/generic_oauth2.py
> +GENERIC_IDP_NAME = "generic"
Sorry i missed all these comments. I forgot about this PR. I opened it some time ago and thought it I had closed it as i had other previous attempts when I was first working with some of the Gen3 folks to understand how to properly get a PR submitted. When i first submitted this one there were a lot of permission issues. I forgot to delete the branch as i had deleted other attempts. This one was replaced eventually by https://github.com/uc-cdis/fence/pull/890. I did incorporate these changes including some code to properly mock the test results on the discovery URL but can also add the additional notes you have. In the 890 PR i did remove the "generic IDP" feature as i was told that was not a design Gen3 folks liked. We have come up with a different more dynamic design but probably need to have a conversation to understand how we can do it better. So the new PR is narrowed down to just Okta.  However i will add those updated to mock user id. 

Let me know if you would like to close this PR or have me close it.

2021-04-19 20:53 UTC, cginmn commented
Deleting branch as this was replaced with PR 890.

2021-04-19 20:53 UTC, closed without merging