PXP-7805 Push audit logs to an AWS SQS
uc-cdis/fence pull request #923
Opened 2021-05-26 14:45 UTC by paulineribeyre

Jira Ticket: [PXP-7805](https://ctds-planx.atlassian.net/browse/PXP-7805)

goes with https://github.com/uc-cdis/audit-service/pull/2 and https://github.com/uc-cdis/cloud-automation/pull/1603

### New Features
- Fence can be configured to push audit logs to an AWS SQS
- Record all requests instead of only successful requests by creating audit logs right before returning the response

### Breaking Changes

### Bug Fixes

### Improvements
- Audit logs for login events now have the "code" and "state" query parameters redacted
- Fence unit tests for login events now test all available IDPs

### Dependency updates

### Deployment changes
- To enable pushing audit logs to an AWS SQS, the "PUSH_AUDIT_LOGS_CONFIG" configuration needs to be updated manually (add "type: aws_sqs", and the SQS URL and region can be copied from the audit-service configuration)

2021-05-26 15:27 UTC, Avantol13 commented on fence/config-default.yaml
> +  type: aws_sqs
defaulting to this means that existing deployments with ENABLE_AUDIT_LOGS on will now error until they flip this to `api`, right? We may want to note that in `DEPLOYMENT CHANGES`. I know you note something about enabling them, but may want to explicitly mentioned that even for deployments that DON'T want this, they have to update the cfg (unless you change this default)

2021-05-26 15:32 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +    if not protocol and len(indexed_file.indexed_file_locations) > 0:
shouldn't the truthy check above already handle this?

2021-05-26 15:37 UTC, paulineribeyre commented on fence/blueprints/data/indexd.py
> +    if not protocol and len(indexed_file.indexed_file_locations) > 0:
which check? if the indexd record `urls` field is empty, we need to check this here - we record no protocol, and then the presigned URL generation function errors 'there are no locations'

2021-05-26 15:37 UTC, Avantol13 commented on fence/__init__.py
> +@app.after_request
is this called after every request? :grimacing: I'm a little nervous of the overhead of this. I like the idea of consolidating and making it cleaner, but could we isolate this cleaning logic to only functions where we know we're capturing audit logs?

Maybe make a custom decorator and only decorate functions we know we want to audit log? Also only do the decorator logic if audit logs are enabled.

I also want to make sure that if someone doesn't want ANY logging, it shouldn't impact performance

2021-05-26 15:39 UTC, paulineribeyre commented on fence/__init__.py
> +@app.after_request
good point, i'll look into that

2021-05-26 15:39 UTC, Avantol13 commented on fence/__init__.py
> +@app.after_request
Maybe something like [this conditional decorator](https://stackoverflow.com/questions/10724854/how-to-do-a-conditional-decorator-in-python) based on if audit logs are enabled. And then this function basically becomes a decorator only used when it's enabled and only on functions where we know we want to audit log.

2021-05-26 15:42 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +    By default, cast `sub` to str. Use `sub_type` to override this behavior.
why not just always cast to string?

2021-05-26 15:46 UTC, Avantol13 commented on fence/resources/audit_service_client.py
> +    def create_audit_log(self, category, data):
You have another function called `create_audit_log` in a different module. Probably fine but _might_ be confusing. Pending if/how we do the decorator/performance improvements

2021-05-26 15:52 UTC, paulineribeyre commented on fence/blueprints/data/indexd.py
> +    By default, cast `sub` to str. Use `sub_type` to override this behavior.
I didn't look too much into it, but `authutils.current_token["sub"]` is a string and `flask.g.user.id` is an int 🤔
I'm casting `authutils.current_token["sub"]` to int here because audit-service expects an int, to match the type of `sub` in the fence DB.

2021-05-26 15:52 UTC, Avantol13 commented on tests/test-fence-config.yaml
> +  type: api
we should also write some tests that monkey patch this and add others for `aws_sqs` and mock out the AWS call for better coverage of the new feature

2021-05-26 15:53 UTC, Avantol13 requested changes
See comments. tl;dr I think we should isolate this more to reduce potential impact to performance

2021-05-26 15:54 UTC, paulineribeyre commented on tests/test-fence-config.yaml
> +  type: api
Yeah the current tests are testing "type: api", so the audit_service_client module without the SQS part. Tbh I wasn't sure how to test it since _everything_ would be mocked. But i'll spend some more time on that

2021-05-26 15:55 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> +    if not protocol and len(indexed_file.indexed_file_locations) > 0:
sorry, I meant the previous code. like why are we switching from `indexed_file.indexed_file_locations` to `len(indexed_file.indexed_file_locations) > 0`. For situations where urls are empty the previous code should have been `False`.

2021-05-26 17:58 UTC, paulineribeyre commented on fence/blueprints/data/indexd.py
> +    if not protocol and len(indexed_file.indexed_file_locations) > 0:
woops, yeah i'm not sure what happened there 😆

2021-05-26 18:05 UTC, paulineribeyre commented on fence/config-default.yaml
> +  type: aws_sqs
done

2021-05-27 21:06 UTC, Avantol13 commented on fence/resources/audit/client.py
> +        max_tries = 3
can you use backoff lib for this to remain consistent? we're using it elsewhere https://github.com/uc-cdis/fence/blob/b85118f4b0bbcba5de6a856ef275f7c45ef3b687/fence/resources/openid/ras_oauth2.py#L118

2021-05-27 21:07 UTC, Avantol13 commented on fence/resources/audit/client.py
> +        max_tries = 3
you can override the exception/handling of default if you need to

2021-05-27 21:10 UTC, Avantol13 commented on fence/resources/audit/client.py
> +            logger.warn("NOT enabling audit logs")
`.warn` is deprecated I believe. you should use `.warning`

2021-05-27 21:11 UTC, Avantol13 commented on fence/resources/audit/client.py
> +    def validate_config(self):
Don't hate me. I'm tempted to ask if we get some docstrings for all these public functions. Granted I think most are self explanatory. But for consistency, eh :shrug:

2021-05-27 21:16 UTC, Avantol13 commented on fence/resources/audit/utils.py
> +def clean_request_url(request_url):
minor thing, but if this is only handling Authorization requests and only used in here, we maybe want to make this something like `_clean_authorization_request_url` so that people only think this is cleaning any request of sensitive data

2021-05-27 21:19 UTC, Avantol13 commented on fence/resources/audit/utils.py
> +                **flask.g.audit_data,
do you need `if hasattr(flask.g, "audit_data"):` before this? Alternatively, you could use `getattr(flask.g, "audit_data", some_default)` I think

2021-05-27 21:21 UTC, Avantol13 commented on fence/resources/audit/utils.py
> +        request_url = clean_request_url(request_url)
do you only need this for logins? and do we only ever want to try to log if there's info in flask.g.audit_data ?  If so, you could move this into the /login block and do the flask.g.audit_data check before the endpoint blocks below

2021-05-27 21:26 UTC, Avantol13 commented on tests/test-fence-config.yaml
> +  type: api
well just the boto call out to sqs would need to be mocked, you could check that it actually gets called with expected data

2021-05-27 21:28 UTC, Avantol13 commented on tests/test_audit_service.py
> +def test_push_to_audit_sqs(
I might have just missed it, but if you don't already have one for the /login audit log can you add a test for that too :pray: 
?

2021-05-27 21:29 UTC, Avantol13 commented on tests/test-fence-config.yaml
> +  type: api
oh, I see you added some :confetti_ball:

2021-05-27 21:29 UTC, Avantol13 commented on fence/resources/audit/utils.py
> +def enable_audit_logging(f):
:sparkles: neat :sparkles:

2021-05-27 21:31 UTC, Avantol13 commented on fence/resources/audit/utils.py
> +def enable_audit_logging(f):
if I'm reading this correctly and I add this to some random function for an endpoint that's NOT /login or /data/download then nothing will happen, right? Basically it'll still get into `create_audit_log_for_request` but it'll just miss all the conditions and return. e.g. you'd have to add more code into that function to catch the request

2021-05-27 23:58 UTC, paulineribeyre commented on fence/resources/audit/utils.py
> +        request_url = clean_request_url(request_url)
I was thinking `clean_request_url` might be needed for other endpoints in the future 🤔 but yeah for now it could go into the login block

2021-06-01 14:50 UTC, paulineribeyre commented on fence/resources/audit/utils.py
> +                **flask.g.audit_data,
i won't use `if hasattr(flask.g, "audit_data")` because we should record requests that failed before `flask.g.audit_data` was populated. `getattr` is a good idea 😄

2021-06-01 19:45 UTC, Avantol13 commented on fence/resources/audit/utils.py
> +    except:
```suggestion
    except Exception:
```

2021-06-01 19:49 UTC, Avantol13 approved these changes

2021-06-11 15:39 UTC, merged