Feat/atlas hacks
uc-cdis/fence pull request #948
Opened 2021-07-20 14:39 UTC by rnerella92

Jira Ticket: [PXP-7690](https://ctds-planx.atlassian.net/browse/PXP-7690)

Setup Atlas login through Fence with OIDC, it will provide more flexible authentication flow, in contrast of current all-or-nothing approach.

### New Features

### Breaking Changes

### Bug Fixes
PXP-7690

### Improvements

### Dependency updates

### Deployment changes

2021-07-20 15:29 UTC, paulineribeyre commented on .secrets.baseline
> +<<<<<<< HEAD
lots of conflicts in this file - you need to re-build the lock file

2021-07-20 15:29 UTC, paulineribeyre commented on fence/blueprints/user.py
> +    info["sub"] = str(info["sub"])
why is this an "atlas hack"?
and if we need to do this, let's do it in function `get_user_info` instead. You might need to update the API docs for this endpoint

2021-07-20 15:29 UTC, paulineribeyre commented on fence/jwt/keys.py
> +        jwk_dict.update({"use": "sig", "key_ops": ["verify"], "kid": self.kid})
could you explain this change? and again, the API docs for this endpoint might need an update

2021-07-20 15:29 UTC, paulineribeyre commented on fence/jwt/token.py
> +    audiences = audiences + scopes
`audiences` is never used. could you explain this change?

2021-07-20 18:47 UTC, rnerella92 commented on .secrets.baseline
> +<<<<<<< HEAD
Updated the secrets file.

2021-07-27 17:50 UTC, m0nhawk commented on fence/blueprints/user.py
> +    info["sub"] = str(info["sub"])
This is a non-complaint to the standard, per [OpenID](https://openid.net/specs/openid-connect-basic-1_0.html#rfc.section.2.2):
```
The sub value is a case sensitive string
```

The comment is redundant. :)

2021-07-27 17:55 UTC, m0nhawk requested changes
@rnerella92 Some extra comments.

2021-07-27 17:55 UTC, m0nhawk commented on fence/jwt/keys.py
> +        jwk_dict.update({"use": "sig", "key_ops": ["verify"], "kid": self.kid})
Again, this is non-complaint with the standard — [RFC7517](https://datatracker.ietf.org/doc/html/rfc7517#section-4.3):

```
Its value is an array of key operation values.
```

2021-07-27 17:55 UTC, m0nhawk commented on fence/jwt/token.py
> +    audiences = audiences + scopes
I'm not sure on this one. It looks like it's safe to remove.

2021-07-27 18:01 UTC, Avantol13 commented on fence/blueprints/user.py
> +    info["sub"] = str(info["sub"])
I believe the suggestion was to do it here instead: https://github.com/uc-cdis/fence/blob/e2779111dce9a5db4de850a0ecc785373597b70b/fence/resources/user/__init__.py#L80 as this is the most low level support for constructing userinfo

2021-07-27 18:04 UTC, Avantol13 commented on fence/jwt/token.py
> +    audiences = audiences + scopes
Let's remove it then

2021-07-28 15:09 UTC, m0nhawk commented on fence/blueprints/user.py
> +    info["sub"] = str(info["sub"])
@rnerella92 and did you commit this change in the place Alex suggested?

2021-07-28 16:34 UTC, m0nhawk commented
@Avantol13 Can you take a look again if everything is addressed?

2021-07-28 21:07 UTC, Avantol13 approved these changes

2021-07-29 17:02 UTC, m0nhawk approved these changes

2021-07-29 19:53 UTC, merged