(PXP-8679): Add new db table and update login to add entries
uc-cdis/fence pull request #963
Opened 2021-09-21 20:24 UTC by BinamB

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features
- Add idp_to_user table that maps multiple IdP's to a single user (Currently only using for RAS)

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

- Requires database migration. Adding a new table to Fence.

2021-09-22 14:29 UTC, Avantol13 commented on fence/blueprints/data/indexd.py
> -
could leave this line

2021-09-22 14:29 UTC, Avantol13 commented on fence/blueprints/ga4gh.py
> -
could leave this line

2021-09-22 14:31 UTC, Avantol13 commented on fence/resources/openid/idp_oauth2.py
> +        idp_id = idp.id
what if idp is not found, e.g. None. we need to handle that case

2021-09-22 14:33 UTC, Avantol13 commented on fence/blueprints/login/ras.py
> +                    user, userinfo.get("sub"), "ras"
should maybe use `IdentityProvider.ras` instead of "ras" string

2021-09-22 14:44 UTC, Avantol13 requested changes
left a few comments

2021-09-23 14:49 UTC, BinamB commented on fence/resources/openid/idp_oauth2.py
> +        idp_id = idp.id
Okay so what I was thinking was that this is what happens post login which means that the user has already logged in through the idp. Even the input for `provider` is  `IdentityProvieder.ras` which means we know that it already exists. In term of us using this function for other idps it would still be post login so we know that this idp is already registered? Ohhh but i do see it as Im typing this. Its not just about logging in i guess. What if we get an idp from a different passport that we haven't seen before. We might be leveraging the same code. So I guess we should add the idp to our db in the case where we havent seen this passport issuer before :thinking:

2021-09-28 18:23 UTC, Avantol13 requested changes
need some unit tests for this new behavior as well

2021-09-28 18:23 UTC, Avantol13 commented on fence/models.py
> +    sub = Column(String(), primary_key=True)
actually we can't have this be the primary key b/c diff idps could have diff subs. we need to make a combined primary key of sub+idp.id

2021-09-28 18:23 UTC, Avantol13 commented on fence/models.py
> +class IdPUser(Base):
Maybe this should match Camel Case to the table name for clarity? `IdpToUser` ?

2021-09-28 18:23 UTC, Avantol13 commented on fence/blueprints/login/ras.py
> +        if not user.idp_to_users:
not sure how we need to handle this, but this is gonna break if the db is not migrated yet. I think we can figure that stuff out later when we're ready to merge this whole branch

2021-09-28 18:23 UTC, Avantol13 commented on fence/blueprints/login/base.py
> +                name=provider, description="IdP from foreign Passport"
we should make sure we only do this after the passport has been validated/verified. we don't want to add things to our db from unknown sources if we can't at least verify the signature

2021-09-28 18:23 UTC, Avantol13 commented on fence/blueprints/login/ras.py
> +            except Exception as e:
in what situation are we expecting this to fail?

2021-09-29 21:11 UTC, BinamB commented on fence/blueprints/login/base.py
> +                name=provider, description="IdP from foreign Passport"
Okay moved in ras.py to do it only if its been validated. I'll leave a note in the function saying that we should only do this iff passport has been validated

2021-09-29 21:13 UTC, BinamB commented on fence/blueprints/login/ras.py
> +        if not user.idp_to_users:
Dont we usually put this  stuff in the deployment changes so devops knows we need to do a db migration. Thats what i've  seen in the past but yeah with all the changes we're going to have we'll need to figure that out

2021-09-30 15:40 UTC, Avantol13 commented on fence/models.py
> +        Integer, ForeignKey(IdentityProvider.id, ondelete="CASCADE"), nullable=False
in order to make a multi-column primary key (idp+sub) I think you need this:
```suggestion
        Integer, ForeignKey(IdentityProvider.id, ondelete="CASCADE"), nullable=False, primary_key=True
```

2021-09-30 15:40 UTC, Avantol13 commented on fence/models.py
> +        Integer, ForeignKey(IdentityProvider.id, ondelete="CASCADE"), nullable=False
you should recreate the table and ensure that's what happens, but I think that's how it should work

2021-10-01 16:12 UTC, Avantol13 approved these changes

2021-10-01 17:31 UTC, merged