Feat/multi passport
uc-cdis/fence pull request #967
Opened 2021-10-06 16:44 UTC by BinamB

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features
- Support multi-passport validation
- Create a list of "Global" sub from passports

2021-10-06 18:50 UTC, Avantol13 requested changes

2021-10-06 18:50 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +        logger.error(
you log the error but then continue execution, is that intentional? Or should this re-raise the exception?

2021-10-06 18:50 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +GLOBAL_USER_SUB_FROM_PASSPORT = []
either we might want a more OOO approach with wrapper class for all this passport/visa stuff?


```
PassportsInfo = object
PassportsInfo.subs = []
PassportsInfo.passports = [passport1, passport2]

Passport = object
Passport.visas = []
```

and then you create/pass around the `PassportsInfo` object? maybe we could leave this as a refactor for later, at a minimum, we should be using a real global var here

2021-10-06 19:09 UTC, BinamB commented on fence/resources/ga4gh/passports.py
> +        logger.error(
Yeah it was intentional but let me know if this makes sense. So if we dont get iss or kid then that means the passport is malformed and this function eventually just returns `[]`. I can comment this if doing this makes sense

2021-10-06 19:09 UTC, BinamB commented on fence/resources/ga4gh/passports.py
> +        logger.error("Passport failed validation: {}. Discarding passport.".format(e))
same as above. Empty list if passport is invalid.

2021-10-06 19:20 UTC, johnfrancismccann commented on fence/blueprints/ga4gh.py
> +        raise UserError("Passports not supported yet")
Maybe we could add a `TODO` comment reminding us to take this line (`raise UserError ...`) out at a later point (or maybe take it out right now since we're not merging to `master` yet).

2021-10-06 20:11 UTC, BinamB commented on fence/blueprints/ga4gh.py
> +        raise UserError("Passports not supported yet")
Yeah you're right. Removing it. It's just gonna be in our developer branch

2021-10-29 18:10 UTC, BinamB commented on fence/resources/openid/ras_oauth2.py
> -                if "kty" in key and key["kty"] == "RSA":
Yup! Its done in authutils here https://github.com/uc-cdis/authutils/blob/4b43a250f448815f1ea0e7fa22fa0b02c9a2cb1d/src/authutils/token/keys.py#L136

2021-11-01 17:39 UTC, Avantol13 approved these changes

2021-11-01 18:32 UTC, merged