(PXP-8682): Add visa validation and sync for data download
uc-cdis/fence pull request #973
Opened 2021-10-20 14:30 UTC by johnfrancismccann

Jira Ticket: [PXP-8682](https://ctds-planx.atlassian.net/browse/PXP-8682)

### New Features
- Visa validation and authz sync for POST /data/download/{guid} endpoint

### Deployment changes

- Requires a database migration to create `iss_sub_pair_to_user` table

2021-11-09 17:40 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +        issuers=config.get("GA4GH_VISA_ISSUER_ALLOWLIST", []),
if you're using config you don't have to .get(), you can access directly and it will default to whatever is in the default config file. so just 
```suggestion
        issuers=config["GA4GH_VISA_ISSUER_ALLOWLIST"],
```

2021-11-09 20:39 UTC, johnfrancismccann commented on fence/resources/ga4gh/passports.py
> +        for raw_visa in raw_visas:
Note that this for loop is indented within `for passport in passports`. The reason for this is the assumption that `min_visa_expiration` should be calculated for all visas within a single passport, as opposed to all visas across all passports.

2021-11-09 21:24 UTC, Avantol13 commented on fence/config-default.yaml
> +GA4GH_VISA_V1_CLAIM_REQUIRED_FIELDS:
we may want to section off all the ga4gh/ras specific config with something like: 
```
# //////////////////////////////////////////////////////////////////////////////////////
# DATA ACCESS: GA4GH SUPPORT AND AUTHORIZATION SYNCING
# //////////////////////////////////////////////////////////////////////////////////////
```

2021-11-09 21:49 UTC, Avantol13 commented on fence/blueprints/login/ras.py
> -                    self.map_user_idp_info(
does this happen later now? it seems like we still need to add entries to this table on login if possible

2021-11-09 22:27 UTC, johnfrancismccann commented on fence/blueprints/login/ras.py
> -                    self.map_user_idp_info(
It actually happens earlier now, in `get_user_id` in `ras_oauth2.py`, just before a user is logged in. This was so that we can handle the cases when we change the username from a prior DRS access request (instead of creating a duplicate user) or when we want to prefer the prior DRS user over the stale user from an earlier login.

2021-11-09 22:43 UTC, Avantol13 requested changes

2021-11-09 22:43 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +        delete_expired_google_access_job_frequency = config.get(
we should name this something else since it's not just the google job but also the arborist job. Maybe it should be `EXPIRED_AUTHZ_REMOVAL_JOB_FREQ_IN_SECONDS` ?

2021-11-09 22:43 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +            usernames_from_current_passport.append(gen3_user.username)
I believe this function should return a list of the `gen3_user`'s. Later when we only need their usernames we can do that. But it's going to be more extensible to pass around the references to the users in case we ever need anything other than the usernames. Or even just change the caller of this function to immediately make a list of just of the usernames, but the function returns all the users

2021-11-09 22:43 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +                "the passport's minimum visa expiration time fell within "
we should alter this text, b/c this could also mean that the expiration is before now(). basically it's already expired or it will expire before the next authorization expiration job can run

2021-11-09 22:43 UTC, Avantol13 commented on fence/config-default.yaml
> +  type: "https://ras.nih.gov/visas/v1.1"
we are going to want all these to be lists of allowed/possible values

2021-11-09 22:43 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +    # TODO check that there is no JKU field in header?
do we need to do this?

2021-11-09 22:43 UTC, Avantol13 commented on fence/__init__.py
> +        issuer = app.ras_client.get_value_from_discovery_doc("issuer", "")
not sure how I feel about this block. I think this should be something we try to configure ahead of time to reduce this startup call. we can add an optional `token_issuer` to the configured clients under the `OPENID_CONNECT` configuration block

2021-11-09 22:43 UTC, Avantol13 commented on fence/__init__.py
> +        issuer = app.ras_client.get_value_from_discovery_doc("issuer", "")
we actually already have `GA4GH_VISA_ISSUER_ALLOWLIST`, we could maybe merge that with the `OPENID_CONNECT` block? list of iss per client. We already use this block to setup the ras_client https://github.com/uc-cdis/fence/blob/d38c08ecd2bc7abef8835715c4a784cbea46b081/fence/job/visa_update_cronjob.py#L47-L57 . On startup we could construct `issuer_to_idp` using only configuration and not reaching out externally.


when we add ourselves we'll have to have some concept of `_self` for IdP or something but we can figure that out later

2021-11-09 22:43 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +            sync_visa_authorization(gen3_user, ga4gh_visas, min_visa_expiration)
you pass in `min_visa_expiration` but I think later it pulls the `expires` from the visa. We need to make sure that what you pass in overrides that or that later where it's used it still takes into account the authz job freq

2021-11-09 22:43 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +            sync_visa_authorization(gen3_user, ga4gh_visas, min_visa_expiration)
also I think we need to rework/rethink `sync_single_user_visas` in general... it currently removes all visas before adding the ones provided. So this loop you have here will overwrite anything for subsequent iss/sub pairs if it's for the same `gen3_user` . For now... we don't expect multiple Gen3 users in a single RAS Passport, but this will be a problem in the future.

2021-11-10 15:39 UTC, johnfrancismccann commented on fence/resources/ga4gh/passports.py
> +        if not raw_visas:
Yeah no problem, and an empty `raw_visas` list could also mean that the passport wasn't valid, since `get_unvalidated_visas_from_valid_passport` returns an empty list for an invalid passport.

2021-11-10 18:09 UTC, johnfrancismccann commented on fence/resources/ga4gh/passports.py
> +            sync_visa_authorization(gen3_user, ga4gh_visas, min_visa_expiration)
Would there still be overwriting of old visa policies even with [this change](https://github.com/uc-cdis/fence/pull/973/files#r746023680)? Not seeing where else that would happen.

2021-11-10 21:16 UTC, Avantol13 commented on fence/blueprints/login/ras.py
> -                    self.map_user_idp_info(
ohh, okay that makes sense. I'll take another look with that in mind

2021-11-10 21:22 UTC, Avantol13 commented on fence/config-default.yaml
> +  type: "https://ras.nih.gov/visas/v1.1"
or exclude it from the configuration entirely and just embed that logic in the code itself (if you don't expect we'll ever need to change it)

2021-11-10 21:22 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +        if not raw_visas:
ooh very good point, yeah definitely add a comment clarifying all that

2021-11-10 21:22 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +                "the passport's minimum visa expiration time fell within "
yeah maybe something generic like: `The passport's earliest valid visa expiration time is set to occur within {EXPIRED_AUTHZ_REMOVAL_JOB_FREQ_IN_SECONDS} seconds from now, which is too soon an expiration to handle.`

2021-11-10 21:25 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +    # TODO check that there is no JKU field in header?
hmm we may want to check for this and raise a notimplemented exception or something? `We do not currently support Visa Document Tokens by passing `jku` in the header. We only support Visa Access Tokens`

2021-11-10 21:48 UTC, Avantol13 commented on fence/sync/sync_users.py
> +                self.arborist_client.revoke_all_policies_for_user(username)
trying to think this through.. so if `single_user_sync` is True, we always expect that an expiration is set on the arborist policy such that it's removed at the right time. But won't this create new policies for every request with a new passport (I guess this might be expected)? What about with the same passport? Will this mean that if I send 500 requests with the same passport I get 500 policies in Arborist? Or does this code already handle those conflicts?

2021-11-11 15:45 UTC, johnfrancismccann commented on fence/sync/sync_users.py
> +                self.arborist_client.revoke_all_policies_for_user(username)
New policies will be created for every request with a new passport assuming each POSTed passport has a different set of dbgap permissions. New policies won't be created for overlapping dbgap permissions across different passports/requests. 

So for 500 requests with [this sample passport](https://sts.nih.gov/passport/dbgap/v1.1), only two policies would be created in Arborist: `programs.phs000021.c1-read` and `programs.phs000021.c1-read-storage`. The policy name is only [created](https://github.com/uc-cdis/fence/blob/defadaab9916317828a64559effdc44f014d64c5/fence/sync/sync_users.py#L1703) based off of study id, consent group, and permission.

Below are Arborist logs for POSTing the sample passport on my laptop for the second time (username redacted).
```
::1 - - [11/Nov/2021:06:57:28 -0800] "GET /health HTTP/1.1" 200 0 "" "python-httpx/0.20.0"
::1 - - [11/Nov/2021:06:57:28 -0800] "GET /resource/programs/phs000021.c1 HTTP/1.1" 200 124 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 response.go:85: INFO: failed to insert user: user with this ID already exists: <redacted>
::1 - - [11/Nov/2021:06:57:28 -0800] "POST /user HTTP/1.1" 409 146 "" "python-httpx/0.20.0"
::1 - - [11/Nov/2021:06:57:28 -0800] "GET /health HTTP/1.1" 200 0 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 response.go:85: INFO: failed to insert user: user with this ID already exists: <redacted>
::1 - - [11/Nov/2021:06:57:28 -0800] "POST /user HTTP/1.1" 409 146 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 response.go:85: INFO: failed to insert role: role with this ID already exists: read-storage
::1 - - [11/Nov/2021:06:57:28 -0800] "POST /role/ HTTP/1.1" 409 104 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 server.go:667: INFO: overwrote policy programs.phs000021.c1-read-storage
::1 - - [11/Nov/2021:06:57:28 -0800] "PUT /policy/programs.phs000021.c1-read-storage HTTP/1.1" 201 138 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 server.go:1154: INFO: granted policy programs.phs000021.c1-read-storage to user <redacted>
::1 - - [11/Nov/2021:06:57:28 -0800] "POST /user/<redacted>/policy HTTP/1.1" 204 0 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 response.go:85: INFO: failed to insert role: role with this ID already exists: read
::1 - - [11/Nov/2021:06:57:28 -0800] "POST /role/ HTTP/1.1" 409 96 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 server.go:667: INFO: overwrote policy programs.phs000021.c1-read
::1 - - [11/Nov/2021:06:57:28 -0800] "PUT /policy/programs.phs000021.c1-read HTTP/1.1" 201 130 "" "python-httpx/0.20.0"
2021/11/11 06:57:28 server.go:1154: INFO: granted policy programs.phs000021.c1-read to user <redacted>
::1 - - [11/Nov/2021:06:57:28 -0800] "POST /user/<redacted>/policy HTTP/1.1" 204 0 "" "python-httpx/0.20.0"
```
The only thing I would be concerned about is the PUT /policy/{policy_name} request, in which `overwrote policy` gets logged. For example, what if that were overwriting permissions from a separate usersync?

2021-11-11 21:11 UTC, BinamB commented on fence/resources/openid/ras_oauth2.py
>      def update_user_visas(self, user, pkey_cache, db_session=current_session):
I think we should use the `validate_visa` you implemented here as well. We call `update_user_visas` during access token polling that validates both passports and visas. It would be nice to have the same visa validation logic in this job.

2021-11-11 21:11 UTC, BinamB commented on fence/resources/openid/ras_oauth2.py
>      def update_user_visas(self, user, pkey_cache, db_session=current_session):
Oh also reminder that when we're adding the `validate_visa` here we might want to pass `pkey_cache` to the `validate_jwt` function since flask cache wont work while running this job.

2021-11-15 16:04 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +    # TODO use user_ids_from_all_passports that were returned from cache to
I didn't really think through this case, honestly I think it's a bit too much to include this db call without a reason. I hate to reverse course but just handling the IDs here is probably fine for now

2021-11-15 16:04 UTC, johnfrancismccann commented on fence/__init__.py
> +        issuer = app.ras_client.get_value_from_discovery_doc("issuer", "")
Updated so that `issuer_to_idp` is constructed only using configuration. I didn’t nest `GA4GH_VISA_ISSUER_ALLOWLIST` in the `ras` block of `OPENID_CONNECT` in `config-default.yaml` because it was getting overwritten by the local config file when testing.

2021-11-15 16:05 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +    logger.info("Visa was successfully validated")
This should probably have some identifier for the visa in the log

2021-11-15 16:07 UTC, Avantol13 commented on fence/resources/openid/ras_oauth2.py
> +            issuer (str): RAS issuer
Remove "RAS", will eventually map other idps

2021-11-15 16:08 UTC, Avantol13 commented on fence/resources/openid/ras_oauth2.py
> +                        "Changing said user's username to the username "
You should include the actual sub and iss and username previous and future in this log to aide I'm debugging

2021-11-15 16:09 UTC, Avantol13 commented on fence/resources/openid/ras_oauth2.py
> +                        "to the RAS user who is currently trying to log in: one "
Same as above comment

2021-11-15 16:37 UTC, johnfrancismccann commented on fence/resources/ga4gh/passports.py
> +    # TODO use user_ids_from_all_passports that were returned from cache to
So would that mean that `get_gen3_users_from_ga4gh_passports` should return a list of user ids or usernames? If a list of user ids is returned, then a later db query would still be necessary to determine usernames for the later Arborist authz check.

I think the minimum number of db queries would be made by having the cache store usernames and `get_gen3_users_from_ga4gh_passports` also return usernames.

2021-11-17 17:13 UTC, Avantol13 commented on fence/resources/ga4gh/passports.py
> +    # TODO use user_ids_from_all_passports that were returned from cache to
yeah, I agree. Let's do usernames for now. If in the future we need more/something else, we'll handle it then

2021-11-17 20:48 UTC, johnfrancismccann commented on fence/resources/ga4gh/passports.py
> +    logger.info("Visa was successfully validated")
Updated. Logged `jti` and `txn` above just after call to `validate_jwt`

2021-11-17 21:36 UTC, johnfrancismccann commented on fence/resources/openid/ras_oauth2.py
> +                self.logger.info(
Added a `create_user` function in `fence/models.py` that is now used for [DRS access](https://github.com/uc-cdis/fence/pull/973/files#diff-6eb903144ac0e54f46571c6b7a5825bae74dc9122c01bd99c2defa609a11bf5cR290) and during [RAS login](https://github.com/uc-cdis/fence/pull/973/files#diff-55adb0b16b1bdae657a354a20608d0a97bafc22eee42b2ff55d9a0e51baf9434R228). I think it would be tricky to also use `create_user` in [`login_user`](https://github.com/uc-cdis/fence/blob/7880778fef77655d27ff245eef2aeee115903c43/fence/auth.py#L98) because of a possible code path in which the user already exists but idp isn't linked yet.

2021-11-17 21:46 UTC, Avantol13 approved these changes

2021-11-17 21:48 UTC, merged